### PR TITLE
Add error handling for JointAxis::SetXyz and remove use of use_parent_model_frame

### PR DESCRIPTION
**Pull request by azeey**
As of https://github.com/osrf/sdformat/pull/312, `JointAxis::SetXyz` returns an `sdf::Errors`. A warning is emitted if the return is ignored, so this PR adds error handling for it. In addition, https://github.com/osrf/sdformat/pull/312 enforces normalization of the input XYZ vector, so I have updated the test expectations in this PR.

This PR also removes the use of `use_parent_model_frame` since it was deprecated in Citadel and should be removed in Dome. I will create a followup PR in ign-msgs to remove it, but that's not required for this PR.

### CODE REVIEW

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
the changes look good to me, but I'm not sure about the CI failures

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
I think we need a pre-release of sdformat to fix the homebrew CI failures. The Ubuntu CI failures have been fixed by https://github.com/ignitionrobotics/ign-gazebo/pull/271, but it hasn't made its way to master yet.

**Comment by scpeters** [comment]
> I think we need a pre-release of sdformat to fix the homebrew CI failures. The Ubuntu CI failures have been fixed by #271, but it hasn't made its way to master yet.

the prerelease has been made

@osrf-jenkins run tests please

**Comment by azeey** [comment]
Sorry @scpeters, I should have been more specfic. We actually need a prerelease of sdf10 for this since it needs https://github.com/osrf/sdformat/pull/312.

**Comment by scpeters** [comment]
actually we need another sdformat10 prerelease for this. I'll work on that too

**Comment by scpeters** [comment]
> Sorry @scpeters, I should have been more specfic. We actually need a prerelease of sdf10 for this since it needs [osrf/sdformat#312](https://github.com/osrf/sdformat/pull/312).

the prerelease is building; I'll restart the jenkins jobs once it is finished

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by azeey** [comment]
New builds
* Ubuntu: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/3895/)
* Homebrew: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/3568/)

Failing tests don't appear to be caused by this PR.

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
I'll close and reopen to trigger CI, not sure why the ubuntu actions are not coming up

**Comment by chapulina** [comment]
> not sure why the ubuntu actions are not coming up

It's because the PR is from a fork, now it will be triggered: 278cde4

**Pull request merged**
