### PR TITLE
Fixed some test - sdf::JointAxis is normalized and some other timers.

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
The SDF converter test is failing because it's saving the URI in both formats file and URL. I thought this was fixed here https://github.com/ignitionrobotics/ign-fuel-tools/pull/85
```
21:       <visual name='visual'>
21:         <geometry>
21:           <mesh>
21:             <uri>file:///root/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Backpack/1/https://fuel.ignitionrobotics.org/1.0/openrobotics/models/Backpack/1/files/meshes/Backpack.dae</uri>
21:           </mesh>
21:         </geometry>
```

**Comment by ahcorde** [comment]
I checked that there are some common parts with this other PR https://github.com/ignitionrobotics/ign-gazebo/pull/288/files

 - This PR fix another compilation warning https://github.com/ignitionrobotics/ign-gazebo/pull/314/commits/dda96b0ab5545cb4b0b0ea469913e23e99278210
 - Some other tests

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
> The SDF converter test is failing because it's saving the URI in both formats file and URL. I thought this was fixed here [ignitionrobotics/ign-fuel-tools#85](https://github.com/ignitionrobotics/ign-fuel-tools/pull/85)
> 
> ```
> 21:       <visual name='visual'>
> 21:         <geometry>
> 21:           <mesh>
> 21:             <uri>file:///root/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Backpack/1/https://fuel.ignitionrobotics.org/1.0/openrobotics/models/Backpack/1/files/meshes/Backpack.dae</uri>
> 21:           </mesh>
> 21:         </geometry>
> ```

I created an issue for this: #322

**Comment by chapulina** [comment]
The joint axis failures should be fixed since #288

**Review by chapulina — APPROVED** [review]

**Pull request merged**
