### PR TITLE
 Extend odom publisher to allow 3D

### LINKED ISSUE #934: Odometry 3D publisher plugin
## Desired behavior
I've been implementing a multicopter in ignition gazebo and I wanted to get a simple plugin that publishes the pose and velocities of the drone. I saw `odometry_publisher` existed and looked at #547. Ideally, this system would estimate the velocities in a similar way and not use the planar assumption. I want to use this plugin to obtain the ground truth of my vehicle.

## Alternatives considered
This could either be done by extending the `odometry_publisher` to handle 3D space or creating a new odometry 3d publisher. As is, the current name is misleading since its logic is derived from `gazebo_ros_planar_move` and only allows for 2D odometry.

## Implementation suggestion
Same implementation as mentioned above.

### PR DESCRIPTION
**Pull request by blakermchale**
Signed-off-by: Blake McHale <mchale.blake@gmail.com>

# 🎉 New feature

Closes #934 and replaces #941.

## Summary
This adds in a new tag `<dimensions>` to the odometry publisher plugin that accepts either 2 or 3 (defaults to 2). When the value is 3 it assumes a 3D assumption instead of planar. This is useful for people who want to know the z location and angular rates. In my use case, I was using the multicopter plugin with the X3 model.

## Test it
This feature can be tested by running the `INTEGRATION_odometry_publisher` test or adding the tag to the plugin in an SDF file. I tested this manually and echoed the odometry topic while commanding the multicopter with velocities.

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Added example and/or tutorial
- [X] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [X] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by blakermchale** [comment]
@chapulina @vatanaksoytezer  This is exactly the same PR as before, but based off a different branch with a cleaner commit history. I made all the requested modifications from the other PR. Thanks for helping me out and let me know if there's anything else I should change!

**Review by chapulina — APPROVED** [review]
Thanks for iterating, @blakermchale ! LGTM. I pushed 879eda371fed30af29f40ef9fa65f59076e929c2 adding the odometry plugin to an example world so people have a reference for how to use it.

**Comment by vatanaksoytezer** [comment]
@chapulina thanks a ton for to review 🥳 . When should we expect this to get synced on Fortress and then released? We want to use Fortress binaries in projects but this was the main feature that was forcing us to use Edifice from source.

**Comment by chapulina** [comment]
> When should we expect this to get this synced on Fortress and then released? 

I'm going to work on it soon, if all goes well I think we can have this in Fortress by the end of the week.

**Comment by vatanaksoytezer** [comment]
That's fast 🏁, thanks @chapulina !

**Comment by chapulina** [comment]
> When should we expect this to get this synced on Fortress and then released? 

Btw, it took a bit longer, but this is released into 5.3 (Edifice) and 6.2 (Fortress).

**Comment by vatanaksoytezer** [comment]
> Btw, it took a bit longer, but this is released into 5.3 (Edifice) and 6.2 (Fortress).

Awesome thanks for letting me know and releasing this, I'll update my Ignition binaries!

**Pull request merged**
