### PR TITLE
mimic joint plugin added

### PR DESCRIPTION
**Pull request by addy1997**
## Summary
 
A simple plugin to mimic joint. 

## Files include 
 * MimicJoint.hh
 * MimicJoint.cc
 * CmakeLists.txt
 * README.md (for instructions to generate .so file)

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

### CODE REVIEW

**Comment by scpeters** [comment]
this looks like a port of the following gazebo classic plugin:

* https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins/blob/master/src/mimic_joint_plugin.cpp

there are some API's that are not supported in ignition-gazebo

**Comment by addy1997** [comment]
> this looks like a port of the following gazebo classic plugin:
> 
>     * https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins/blob/master/src/mimic_joint_plugin.cpp
> 
> 
> there are some API's that are not supported in ignition-gazebo

Okay! Could you elaborate more on what exactly in my code or the API needs to be changed in order to make it workable in ign gazebo?

**Comment by ahcorde** [comment]
Hi @addy1997,

I can see that this package is using ROS. This repository should not contain any kind of ROS dependency. This is the strong reason why we should refuse this contribution. This package should live in its own repository.

**Comment by addy1997** [comment]
> Hi @addy1997,
> 
> I can see that this package is using ROS. This repository should not contain any kind of ROS dependency. This is the strong reason why we should refuse this contribution. This package should live in its own repository.

Hi @ahcorde,

Yes, this is a valid point. Is there a repo for ros_ign gazebo plugins where I can contribute this? Actually, this plugin is useful for many applications.

**Comment by ahcorde** [comment]
Here is the [ros_ign](https://github.com/ignitionrobotics/ros_ign/) repository. There are different ROS versions.

I will close this issue.

**Pull request closed without merging**
