### PR TITLE
Update collision visualization to support nested models

### LINKED ISSUE #767: Update visualize collisions to support 1.8 composition
In Citadel & Dome, which uses SDFormat 1.7, when a sdf model contained collisions, then right-clicking to View > Collisions would display all collisions of the model in orange. In Edifice, this no longer works correctly if the model has nested models.

The current implementation (see https://github.com/ignitionrobotics/ign-gazebo/pull/531 for details) checks links of the model for collision entities but assumes that links will be direct children of the model entity. To support SDFormat 1.8, the implementation needs to consider nested models.

To test this, run `ign gazebo nested_model.sdf`, then in the entity tree right-click `model_00` > View > Collisions and only the sphere will be highlighted in orange.

### PR DESCRIPTION
**Pull request by atharva-18**
Signed-off-by: Atharva Pusalkar <atharvapusalkar18@gmail.com>

# 🦟 Bug fix

Fixes #767 

## Summary
Updates collision visualization to support SDFormat 1.8.
collisions_edifice

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
LGTM, waiting for @jennuine review

**Review by jennuine — COMMENTED** [review]
Thank you for tackling this @atharva-18 and great work so far!

Unfortunately, this does not work for deeply nested models. In the gif, only 2 objects in the scene show collisions but all 5 should be shown when viewing all collisions for `M1`:

Peek 2021-05-18 11-07

Assuming you are using an Edifice workspace, to run this example:

```bash
export IGN_GAZEBO_RESOURCE_PATH=<path to Edifice workspace>/src/ign-gazebo/test/worlds/models
ign gazebo <path to workspace>/src/ign-gazebo/test/worlds/model_nested_include.sdf
```

**Comment by atharva-18** [comment]
@jennuine Thanks for finding that! It's fixed in [`ad5b54b`](https://github.com/ignitionrobotics/ign-gazebo/pull/823/commits/ad5b54ba350f5dc2b41f3ec679e4ad6411057074).

**Comment by ahcorde** [comment]
@atharva-18 is this bug also affecting your wireframe PR?

**Comment by atharva-18** [comment]
@ahcorde Yes, this bug is present in the wireframe visualization. I'll open a PR addressing it once this one gets approved.

**Review by ahcorde — APPROVED** [review]

**Review by jennuine — COMMENTED** [review]
Great work! A few minor comments

**Comment by jennuine** [comment]
Also, I think we should `#include <stack>` at the top of `RenderUtil.cc` (it's in alphabetical order)

https://github.com/ignitionrobotics/ign-gazebo/blob/ad5b54ba350f5dc2b41f3ec679e4ad6411057074/src/rendering/RenderUtil.cc#L18-L23

**Review by jennuine — APPROVED** [review]
Thanks for iterating! LGTM, I believe the failing tests are flaky. @ahcorde can you confirm?

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Pull request merged**
