### PR TITLE
3 to 4

### PR DESCRIPTION
**Pull request by adlarkin**
Forward port `ign-gazebo3` to `ign-gazebo4`. One thing I should note is that this didn't compile without building `ign-gui4` from source, because #456 requires https://github.com/ignitionrobotics/ign-gui/pull/148, which was forward-ported to `ign-gui4` in https://github.com/ignitionrobotics/ign-gui/pull/152. Would it be a good idea to at least do a minor release of `ign-gui4` so that users can build `ign-gazebo4` from source without having to build `ign-gui4` from source as well?

### CODE REVIEW

**Comment by adlarkin** [comment]
https://github.com/ignitionrobotics/ign-gazebo/pull/505/commits/096c5e84b3aad977d21504e5aba52afb56c70e52 fixes codecheck errors introduced by https://github.com/ignition-tooling/action-ignition-ci/pull/26, but there are still quite a bit of warnings: https://gist.github.com/adlarkin/73e41c3a7bd22a7ce67e6352db3fc8f1

#499 removed warnings from `ign-gazebo3`, but there are a significantly larger amount of warnings for `ign-gazebo4`. Do we still want to remove the warnings for `ign-gazebo4`? If so, should that be done here, or in a separate PR?

**Review by chapulina — APPROVED** [review]
LGTM once the `ign-gui4` release is out and we run another round of CI.

**Comment by adlarkin** [comment]
> 096c5e8 fixes codecheck errors introduced by ignition-tooling/action-ignition-ci#26, but there are still quite a bit of warnings

So I found out that I was seeing a lot more warnings because I was running `make codecheck` locally in a Ubuntu Focal container, which defaults to `cppcheck-1.90`, while Ubuntu Bionic defaults to `cppcheck-1.82`. GitHub actions uses Bionic, so we should make sure we are running `make codecheck` locally with whatever `cppcheck` version Bionic uses for consistency.

After running `make codecheck` with the same `cppcheck` version as GitHub actions, I found that there are only a few warnings:
```
Built target cpplint
[/ws/src/ign-gazebo/src/SimulationRunner.hh:74]: (style) struct member 'WorldControl::pause' is never used.
[/ws/src/ign-gazebo/src/SimulationRunner.hh:78]: (style) struct member 'WorldControl::multiStep' is never used.
[/ws/src/ign-gazebo/src/SimulationRunner.hh:83]: (style) struct member 'WorldControl::rewind' is never used.
[/ws/src/ign-gazebo/test/integration/physics_system.cc:644]: (style) The scope of the variable 'firstRun' can be reduced.
[/ws/src/ign-gazebo/test/integration/physics_system.cc:743]: (style) The scope of the variable 'firstRun' can be reduced.
Built target cppcheck
Built target codecheck
```

@chapulina should I go ahead and resolve these warnings while we wait for the `ign-gui4` release?

**Comment by chapulina** [comment]
> @chapulina should I go ahead and resolve these warnings while we wait for the ign-gui4 release?

Sure, go for it :+1: Thanks!

**Comment by adlarkin** [comment]
Codecheck warnings have been resolved in https://github.com/ignitionrobotics/ign-gazebo/pull/505/commits/d963ec14473c0cdc035f634e1e38c12120cedaf7. All that's left is updating the `CMakeLists.txt` to depend on `ign-gui4.1.0` - I'll update this once the [`ign-gui4.1.0` release](https://build.osrfoundation.org/job/ign-gui4-debbuilder/) is successfully completed.

**Pull request merged**
