### PR TITLE
Add view control gui plugin and support orthographic view

### PR DESCRIPTION
**Pull request by iche033**
## Summary

depends on https://github.com/ignitionrobotics/ign-rendering/pull/322

* Updated view controller in Scene3d to support both orbit and orthographic view controller
* Added View Control gui plugin that makes service request to Scene3D to toggle between the two view controllers

I can port the changes here to ign-gui if it helps in merging the two Scene3D classes.

## To Test

Run ign-gazebo, open the GUI plugin menu (3 dots on top right) and select `View Control` plugin. Choose `Orthographic` from the drop down list to see the new view controller.

ortho_view_controller_gazebo

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by chapulina — COMMENTED** [review]
> I can port the changes here to ign-gui if it helps in merging the two Scene3D classes.

Thanks, yeah that will help. The current plan is to deprecate `GzScene3D` in Fortress (https://github.com/ignitionrobotics/ign-gui/issues/137).

**Comment by nkoenig** [comment]
Can you add ortho/perspsection control to the ViewAngle plugin instead of creating a new plugin?

**Comment by iche033** [comment]
> Can you add ortho/perspsection control to the ViewAngle plugin instead of creating a new plugin?

done, merged. 7218ef28ce43c8eee709df1e3a3c443fa98d153d

**Review by nkoenig — APPROVED** [review]

**Comment by iche033** [comment]
The test failures look unrelated: level_manager, depth camera test, etc since the changes in this PR are limited to 2 GUI plugins. I think this is good to merge.

**Pull request merged**
