### PR TITLE
Model Editor: Add Joints to model

### PR DESCRIPTION
**Pull request by mjcarroll**
# 🎉 New feature

## Summary

Use the model editor to insert joints into a model.

## Test it

Load a world, select a model in the entity tree and try adding a new joint from the "plus" menu.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by nkoenig** [comment]
I see a problem when adding a link then a joint. For example:

1. Load `shapes.sdf`
2. Add a link to the box.
3. Add a joint to the box.
4. Step simulation. You'll see the following errors:
```
[Err] [SDFFeatures.cc:384] Could not find link link in model box
[Err] [SDFFeatures.cc:750] The link of the child frame [link] with resolved link name [link] of joint [joint] in model [box] could not be resolved. The joint will not be constructed
```

**Comment by mjcarroll** [comment]
> I see a problem when adding a link then a joint. For example:

I believe it's a sequencing issue in the entity creator, I was able to reproduce and I'm looking at it.

**Comment by nkoenig** [comment]
> > I see a problem when adding a link then a joint. For example:
> 
> I believe it's a sequencing issue in the entity creator, I was able to reproduce and I'm looking at it.

Do you need assistance on this?

**Comment by mjcarroll** [comment]
> Do you need assistance on this?

No, should have fix shortly.

**Review by nkoenig — APPROVED** [review]

**Comment by iche033** [comment]
when I tried adding more than one joint, I see that the first joint will have a valid name, `joint`, but subsequent joint names are empty:
joint_names

**Comment by mjcarroll** [comment]
> when I tried adding more than one joint, I see that the first joint will have a valid name, joint, but subsequent joint names are empty

Investigating

**Comment by mjcarroll** [comment]
Fixed in #1228

**Pull request merged**
