### PR TITLE
Emitter migration

### PR DESCRIPTION
**Pull request by nkoenig**
# 🎉 Cleanup

## Summary

During SubT we created a `particle_emitter2` plugin designed to replace the `particle_emitter` plugin. This PR takes the next steps toward having just one particle emitter system.

I tried to make the series of commits easy to follow:

1. 038b59a70b2cb602a4ae276a9de990e5a421977e: Removed the `particle_emitter` directory
2. 84df8174c49cc707d51e2171e73b09d1f199156e: Copied `particle_emitter2` to `particle_emitter`.
3. 4e39df2d241d44886d80021e09b1f812634705d3: Removed `particle_emitter` test files and example world.
4. c4995167b882e51e91d7d0c14da2226c697f9b3b: Moved `particle_emitter2` test files and example world to `particle_emitter`.
5.  cc6765190cda4c7ef01756752b971953774feacc: Renamed `emitter2` to `emitter` inside the test files and example world.
6. 3038fe0de95db9f30c3540c8a060822e7cbd671d: Fixed the integration test.
7. deaf1b1a7d11721c67b50411a49ee3e31736fa73: Updated the tutorial and `lrauv` world.

## Checklist
- [x] Signed all commits for DCO
- [x] Updated documentation (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by iche033 — COMMENTED** [review]
looks good to me. Add an entry to the migration guide?

**Comment by nkoenig** [comment]
Migration guide updated in [9f7648a](https://github.com/ignitionrobotics/ign-gazebo/pull/1287/commits/9f7648aa3ca5c497045f45d42339e0b0618fe455)

**Comment by iche033** [comment]
hmm something is not quite right with the [ubuntu build](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/8008/). The test failures don't look related to changes in this PR. I just triggered another build to double check.

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Review by iche033 — APPROVED** [review]
ubuntu build is better now. Don't think that the test failures are related.

**Pull request merged**
