### PR TITLE
⬆️  2.26.0 🏁

### PR DESCRIPTION
**Pull request by chapulina**
Preparing for a last major version 2 release before Blueprint EOLs in 8 days.

Comparison to 2.25.0:

https://github.com/ignitionrobotics/ign-gazebo/compare/ignition-gazebo2_2.25.0...ign-gazebo2

There are no PRs open against `ign-gazebo2`.

### CODE REVIEW

**Review by adlarkin — APPROVED** [review]

**Comment by scpeters** [comment]
it looks like homebrew CI for this failed with a seg-fault during doc generation

~~~
[  2%] Generating API documentation with Doxygen
warning: Tag 'TCL_SUBST' at line 232 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 1019 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'PERL_PATH' at line 2084 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2106 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
make[2]: *** [CMakeFiles/doc] Segmentation fault: 11
make[1]: *** [CMakeFiles/doc.dir/all] Error 2
~~~

**Comment by scpeters** [comment]
> it looks like homebrew CI for this failed with a seg-fault during doc generation
> 
> ```
> [  2%] Generating API documentation with Doxygen
> warning: Tag 'TCL_SUBST' at line 232 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'COLS_IN_ALPHA_INDEX' at line 1019 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'PERL_PATH' at line 2084 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> warning: Tag 'MSCGEN_PATH' at line 2106 of file '/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/build/api_tagfile.dox' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> make[2]: *** [CMakeFiles/doc] Segmentation fault: 11
> make[1]: *** [CMakeFiles/doc.dir/all] Error 2
> ```

I'm suspicious of https://github.com/Homebrew/homebrew-core/pull/67817, which updated to doxygen 1.9.0, though it only seems to affect ign-gazebo

**Comment by chapulina** [comment]
> it looks like homebrew CI for this failed with a seg-fault during doc generation

Ah sorry, I assumed that CI was just old, because https://github.com/ignitionrobotics/ign-cmake/pull/136 should have fixed it. Now I see that the PR hasn't been released yet. But in any case, I'm surprised that the warnings would cause a segfault.

**Comment by scpeters** [comment]
> > it looks like homebrew CI for this failed with a seg-fault during doc generation
> 
> Ah sorry, I assumed that CI was just old, because [ignitionrobotics/ign-cmake#136](https://github.com/ignitionrobotics/ign-cmake/pull/136) should have fixed it. Now I see that the PR hasn't been released yet. But in any case, I'm surprised that the warnings would cause a segfault.

it was easy to miss because homebrew has been having lots of builds fail recently for different reasons

I think we need an ign-cmake2 patch release in order for https://github.com/ignitionrobotics/ign-cmake/pull/136 to take effect?

**Comment by chapulina** [comment]
> I think we need an ign-cmake2 patch release in order for ignitionrobotics/ign-cmake#136 to take effect?

Yeah I hope that's all we need :crossed_fingers: https://github.com/ignitionrobotics/ign-cmake/pull/142

**Comment by scpeters** [comment]
I think the patch release won't be enough. I've been testing locally, and fixing those warnings doesn't prevent the seg-fault

I'll move this to an issue

**Comment by scpeters** [comment]
> I think the patch release won't be enough. I've been testing locally, and fixing those warnings doesn't prevent the seg-fault
> 
> I'll move this to an issue

https://github.com/ignitionrobotics/ign-gazebo/issues/520

**Pull request merged**
