### PR TITLE
some world files added

### PR DESCRIPTION
**Pull request by addy1997**
@chapulina, I am continuing this pull-up request from #644. I have included a few world files like camera, sensors, cars, tri-copter. Note: I have taken the mesh files from Google warehouse and constructed the .sdf file by referring to the tutorials on gazebosim.org. 

Thanks

### CODE REVIEW

**Comment by atharva-18** [comment]
@addy1997
Thank you for the PR!. Could you sign-off your commits by `git commit -sm <commit_message>`?. More details can be found [here](https://github.com/ignitionrobotics/ign-gazebo/pull/645/checks?check_run_id=1955393297)

**Comment by addy1997** [comment]
> @addy1997
> Thank you for the PR! Could you sign-off your commits by `git commit -sm <commit_message>`? More details can be found [here](https://github.com/ignitionrobotics/ign-gazebo/pull/645/checks?check_run_id=1955393297)

Done.

**Comment by atharva-18** [comment]
@addy1997 The changes aren't being reflected here. You also need to run `git commit --amend --no-edit --signoff`, and `git push --force-with-lease origin ign-gazebo4`. Thanks!

**Comment by addy1997** [comment]
@atharva-18 

```
adwaitnaik@Mackbook-Air-Adwait ign-gazebo % git status
On branch ign-gazebo4
Your branch is up to date with 'origin/ign-gazebo4'.

nothing to commit, working tree clean
adwaitnaik@Mackbook-Air-Adwait ign-gazebo % git commit --signoff --message "some worlds added"
On branch ign-gazebo4
Your branch is up to date with 'origin/ign-gazebo4'.

nothing to commit, working tree clean
adwaitnaik@Mackbook-Air-Adwait ign-gazebo % git commit --amend --no-edit --signoff
[ign-gazebo4 400ac845] some world files added
 Date: Tue Feb 23 00:58:33 2021 +0530
 37 files changed, 38528 insertions(+)
 create mode 100644 examples/worlds/cars/chevy_pickup/chevy_pickup.sdf
 create mode 100644 examples/worlds/cars/chevy_pickup/meshes/chevy_pickup.dae
 create mode 100644 examples/worlds/cars/chevy_pickup/model/GMC_Pickup_base1.JPG
 create mode 100644 examples/worlds/cars/chevy_pickup/model/GMC_pickup_Dash1.JPG
 create mode 100644 examples/worlds/cars/chevy_pickup/model/GMC_pickup_metal1.JPG
 create mode 100644 examples/worlds/cars/chevy_pickup/model/GMC_pickup_wheel1.JPG
 create mode 100644 examples/worlds/cars/chevy_pickup/model/car_pickup_02_US1.JPG
 create mode 100644 examples/worlds/cars/chevy_pickup/model/car_pickup_2.JPG
 create mode 100644 examples/worlds/cars/porsche/meshes/porsche.dae
 create mode 100644 examples/worlds/cars/porsche/model/car_sports_1.JPG
 create mode 100644 examples/worlds/cars/porsche/model/car_sports_11_US1.JPG
 create mode 100644 examples/worlds/cars/porsche/model/car_sports_2.JPG
 create mode 100644 examples/worlds/cars/porsche/model/car_sports_4.JPG
 create mode 100644 examples/worlds/cars/porsche/model/car_sports_5.JPG
 create mode 100644 examples/worlds/cars/porsche/model/plates_us1.JPG
 create mode 100644 examples/worlds/cars/porsche/porsche.sdf
 create mode 100644 examples/worlds/cars/us_police_car/meshes/us_police_car.dae
 create mode 100644 examples/worlds/cars/us_police_car/model/chassis_gen1.JPG
 create mode 100644 examples/worlds/cars/us_police_car/model/plates_us1.JPG
 create mode 100644 examples/worlds/cars/us_police_car/model/saloon_wheel1.JPG
 create mode 100644 examples/worlds/cars/us_police_car/model/us_police_car_bo1.JPG
 create mode 100644 examples/worlds/cars/us_police_car/us_police_car.sdf
 create mode 100644 examples/worlds/sensors and cameras/flir_gimbal/meshes/flir_gimbal.dae
 create mode 100644 examples/worlds/sensors and cameras/flir_optical_turret/flir_optical_turret.dae
 create mode 100644 examples/worlds/sensors and cameras/flir_optical_turret/model/BRITE_Star.psd
 create mode 100644 examples/worlds/sensors and cameras/hector_thermal_eye.sdf
 create mode 100644 examples/worlds/sensors and cameras/kinect.sdf
 create mode 100644 examples/worlds/sensors and cameras/meshes/hector_thermal_eye.dae
 create mode 100644 examples/worlds/sensors and cameras/meshes/kinect.dae
 create mode 100644 examples/worlds/sensors and cameras/meshes/sonar_ez4.dae
 create mode 100644 examples/worlds/sensors and cameras/meshes/stereo_camera.dae
 create mode 100644 examples/worlds/sensors and cameras/sonar_ez4.sdf
 create mode 100644 examples/worlds/sensors and cameras/stereo_camera.sdf
 create mode 100644 examples/worlds/tricopter/meshes/tricopter.dae
 create mode 100644 examples/worlds/tricopter/model/Metal_Aluminum_Anodized.jpg
 create mode 100644 examples/worlds/tricopter/model/Translucent_Glass_Gold.jpg
 create mode 100644 examples/worlds/tricopter/tricopter.sdf
adwaitnaik@Mackbook-Air-Adwait ign-gazebo % git push --force-with-lease origin ign-gazebo4
Enumerating objects: 59, done.
Counting objects: 100% (59/59), done.
Delta compression using up to 4 threads
Compressing objects: 100% (40/40), done.
Writing objects: 100% (56/56), 3.75 MiB | 2.77 MiB/s, done.
Total 56 (delta 11), reused 52 (delta 9)
remote: Resolving deltas: 100% (11/11), completed with 3 local objects.
To https://github.com/addy1997/ign-gazebo.git
 + a541ebf0...400ac845 ign-gazebo4 -> ign-gazebo4 (forced update)

```

**Review by chapulina — CHANGES_REQUESTED** [review]
Thanks for the contribution, @addy1997 !

> I have taken the mesh files from Google warehouse

Did you check if you have permission to distribute all these files? Each of them may have a different license / copyright.

---

Here are some other thoughts:

* We haven't been adding models inside world folders because that makes it difficult to reuse the models inside other worlds. How do you feel about uploading the models to https://app.ignitionrobotics.org/? This should make them easily available to use in any world with `<include><uri>https://fuel.ignitionrobotics.org....` tags.

* I noticed your vehicles are static and don't have joints. You should consider adding movable links to them, so they can be simulated more realistically.

* Finally, I'd suggest that after you upload the models to Fuel, you also upload the worlds there. We're trying to keep the worlds we install with Ignition Gazebo to a minimum, because that makes the package that people install larger, see https://github.com/ignitionrobotics/ign-gazebo/issues/659

**Comment by addy1997** [comment]
Yes, most of them (cars especially) have royalty-free or non-commercial licenses. I will include it while uploading on fuel.

I agree that adding more models will make the software bulky. I'll add the links and upload the models and worlds on ignition fuel.

As my inference is justified, I am closing this issue. Thanks

**Pull request closed without merging**
