### PR TITLE
Nkoenig/3 to 4 20210113

### PR DESCRIPTION
**Pull request by nkoenig**
Merge 3 to 4.

### CODE REVIEW

**Comment by chapulina** [comment]
I'm not seeing the changes from https://github.com/ignitionrobotics/ign-gazebo/pull/543/ on the diff, not sure what happened

**Comment by nkoenig** [comment]
> I'm not seeing the changes from #543 on the diff, not sure what happened

I'm not sure either. The updates are in place, but I don't know how they got there. See https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo4/tutorials/migration_plugins.md.

**Comment by chapulina** [comment]
> The updates are in place

I don't see the updates :monocle_face: Note that the first change was independently done to that branch. But all others, like `this->connection`, aren't fixed yet.

**Review by chapulina — APPROVED** [review]
I redid the merge and force-pushed to this branch and now I can see the diff.

LGTM with happy CI.

**Pull request merged**
