### PR TITLE
Add const to sdf PBR type pointers

### LINKED ISSUE #610: Conversions.cc error C2440 cannot convert from 'const sdf::v11::Pbr *' to 'sdf::v11::Pbr *' and 'const sdf::v11::PbrWorkflow *' to 'sdf::v11::PbrWorkflow *'
Windows CI fails to build because of conversions from a const to a non-const type.

https://build.osrfoundation.org/job/ign_gazebo-ci-win/64/

https://github.com/ignitionrobotics/ign-gazebo/blob/d50acebae4b65df18928b0a7a9e62a252be1c608/src/Conversions.cc#L277

```
D:\Jenkins\workspace\ign_gazebo-ci-win\ws\ign-gazebo\src\Conversions.cc(277,1): error C2440: 'initializing': cannot convert from 'const sdf::v11::Pbr *' to 'sdf::v11::Pbr *' [D:\Jenkins\workspace\ign_gazebo-ci-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
```

https://github.com/ignitionrobotics/ign-gazebo/blob/d50acebae4b65df18928b0a7a9e62a252be1c608/src/Conversions.cc#L281

```
D:\Jenkins\workspace\ign_gazebo-ci-win\ws\ign-gazebo\src\Conversions.cc(281,1): error C2440: 'initializing': cannot convert from 'const sdf::v11::PbrWorkflow *' to 'sdf::v11::PbrWorkflow *' [D:\Jenkins\workspace\ign_gazebo-ci-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
```

https://github.com/ignitionrobotics/ign-gazebo/blob/d50acebae4b65df18928b0a7a9e62a252be1c608/src/Conversions.cc#L286

```

D:\Jenkins\workspace\ign_gazebo-ci-win\ws\ign-gazebo\src\Conversions.cc(286,1): error C2440: '=': cannot convert from 'const sdf::v11::PbrWorkflow *' to 'sdf::v11::PbrWorkflow *' [D:\Jenkins\workspace\ign_gazebo-ci-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
```

### PR DESCRIPTION
**Pull request by sloretz**
Quick test to see if adding const fixes #610

### CODE REVIEW

**Comment by sloretz** [comment]
ign_gazebo-pr-win seems to have gotten past the failures in `Conversions.cc`, but now there are a bunch more in `Model.cc`. It seems like the Windows job needs a bit of work to pass

```
[37.531s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(39,29): error C2653: 'gazebo': is not a class or namespace name [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(39,36): error C3867: 'ignition::gazebo::v5::Model::Entity': non-standard syntax; use '&' to create a pointer to member [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(39,29): error C2146: syntax error: missing ')' before identifier '_entity' [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(40,45): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(41,1): error C2448: 'dataPtr': function-style initializer appears to be a function definition [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(179,24): error C2653: 'math': is not a class or namespace name [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(179,24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(179,24): error C2143: syntax error: missing ',' before '&' [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(180,1): error C2511: 'void ignition::gazebo::v5::Model::SetWorldPoseCmd(ignition::gazebo::v5::EntityComponentManager &,const int)': overloaded member function not found in 'ignition::gazebo::v5::Model' [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\include\ignition/gazebo/Model.hh(60): message : see declaration of 'ignition::gazebo::v5::Model' [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(182,7): error C2671: 'ignition::gazebo::v5::Model::SetWorldPoseCmd': static member functions do not have 'this' pointers [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(183,19): error C3536: 'poseCmdComp': cannot be used before it is initialized [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(185,26): error C2671: 'ignition::gazebo::v5::Model::SetWorldPoseCmd': static member functions do not have 'this' pointers [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(185,70): error C2065: '_pose': undeclared identifier [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(185,9): error C2672: 'ignition::gazebo::v5::EntityComponentManager::CreateComponent': no matching overloaded function found [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(185,76): error C2780: 'ignition::gazebo::v5::ComponentKey ignition::gazebo::v5::EntityComponentManager::CreateComponent(const ignition::gazebo::v5::Entity,const ComponentTypeT &)': expects 2 arguments - 1 provided [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\include\ignition/gazebo/EntityComponentManager.hh(185): message : see declaration of 'ignition::gazebo::v5::EntityComponentManager::CreateComponent' [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(189,26): error C2065: '_pose': undeclared identifier [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.547s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Model.cc(191,21): error C2671: 'ignition::gazebo::v5::Model::SetWorldPoseCmd': static member functions do not have 'this' pointers [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[37.984s]   SdfEntityCreator.cc
[39.531s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Conversions.cc(1102,55): warning C4244: 'argument': conversion from 'double' to 'uint32_t', possible loss of data [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
[39.531s] C:\Jenkins\workspace\ign_gazebo-pr-win\ws\ign-gazebo\src\Conversions.cc(1103,56): warning C4244: 'argument': conversion from 'double' to 'uint32_t', possible loss of data [C:\Jenkins\workspace\ign_gazebo-pr-win\ws\build\ignition-gazebo5\src\ignition-gazebo5.vcxproj]
```

**Comment by sloretz** [comment]
Added 7114e9b to fix similar `const` issues reported in `Conversionts_TEST.cc` in Bionic CI

**Comment by chapulina** [comment]
Oh thanks, @sloretz . This looks like a duplicate of #607, mind taking a look at that?

**Comment by sloretz** [comment]
Closing in favor of #607

**Pull request closed without merging**
