### PR TITLE
Supply world frame orientation and heading to IMU sensor : DCO fix

### PR DESCRIPTION
**Pull request by adityapande-1995**
Signed-off-by: Aditya <aditya050995@gmail.com>

# 🎉 New feature
Ported from : https://github.com/ignitionrobotics/ign-gazebo/pull/1320 to make the DCO bot happy

## Summary
This PR, along with https://github.com/ignitionrobotics/ign-sensors/pull/186, enables the user to specify named orientation frames like ENU and NED as <localization> reference tags for the IMU sensor. The sensor should output the orientation based on the frame specified in the localization tag.

This should also take into account the orientation of the world and the heading_dec offset in the <spherical_coordiantes> tag. Currently, spherical coordinates tag nly supports the ENU world fame.

## Test it
2 integration tests have been added that use a combination of heading_deg and localization tags to get different orientations for IMUs.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by adityapande-1995** [comment]
The changes here were origianlly approved here : https://github.com/ignitionrobotics/ign-gazebo/pull/1320

**Review by hidmic — APPROVED** [review]
LGTM pending green CI. Thanks @adityapande-1995!

@scpeters any other comments?

**Comment by adityapande-1995** [comment]
Homebrew failures seem unrelated, and ``INTEGRATION_imu_system`` is passing

**Review by scpeters — APPROVED** [review]

**Comment by hidmic** [comment]
@adityapande-1995 @scpeters when will this be forwarded to `main` ?

**Comment by scpeters** [comment]
> @adityapande-1995 @scpeters when will this be forwarded to `main` ?

it can be forward-ported at any time. I'll make an attempt

**Comment by scpeters** [comment]
> > @adityapande-1995 @scpeters when will this be forwarded to `main` ?
> 
> it can be forward-ported at any time. I'll make an attempt

https://github.com/ignitionrobotics/ign-sensors/pull/214

**Comment by hidmic** [comment]
Thanks @scpeters! Now we would just need to do the same here, right?

**Pull request merged**
