### PR TITLE
Limit thruster system's input thrust cmd

### PR DESCRIPTION
**Pull request by iche033**
Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🎉 New feature

## Summary

Add two new params to the thruster system for configuring the min and max input thrust cmd:
* `<max_thrust_cmd>`
* `<min_thrust_cmd>`

This affects both PID and vel controlled thrusters.

## Test it

Run the `INTEGRATION_thruster` test

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
what do you think about cheking if min is bigger than max ? Otherwise LGTM

**Comment by iche033** [comment]
> what do you think about cheking if min is bigger than max ?

added check in d795d0098a071dd3e33bcaf88ea86c3cb79850f3

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1

**Comment by scpeters** [comment]
I just tried merging this forward to `main` and I see some conflicts with https://github.com/ignitionrobotics/ign-gazebo/pull/1269

**Comment by scpeters** [comment]
> I just tried merging this forward to `main` and I see some conflicts with #1269

never mind there is already a merge-forward PR in https://github.com/ignitionrobotics/ign-gazebo/pull/1367, but I think it also is struggling with these conflicts

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1

**Pull request merged**
