### PR TITLE
Model editor: Add links to model

### PR DESCRIPTION
**Pull request by iche033**
# 🎉 New feature

## Summary

This pull request adds a `+` menu button to the Component Inspector for adding links to models. Currently supports adding links consisting of simple shapes and lights.

The changes are written to the ECM and GUI side and assumes that GUI and server ECM synchronization (#1109) is available. Marked as draft until the newly added entities can be reflected on the server side.

## Test it

1. launch ign gazebo with shapes.sdf world
1. Open the Model Editor GUI plugin by going to top right 3 dots menu and select `Model Editor`
1. Click on one of the shapes, e.g. box
1. Go the Component Inspect and you should see a new `+` button appear on the top bar
1. Click on the `+` button and select a link type to add, .e.g Cylinder
1. Once selected, a black cylinder should now appear at where the original box model is.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by nkoenig** [comment]
Can the ModelEditor not be a plugin, but instead be built into the component inspector? It can still be a separate class that is instantiated by the ComponentInspector. The graphical interface for adding links is in the ComponentInspector, but right now a separate plugin has to be loaded in order to use the menu options.

**Comment by nkoenig** [comment]
One suggestion here: https://github.com/ignitionrobotics/ign-gazebo/pull/1176

**Comment by nkoenig** [comment]
Another suggestion in #1177.

**Comment by iche033** [comment]
> One suggestion here: #1176

merged

> Another suggestion in #1177.

merged

> Adding an ellipsoid link doesn't seem to add the collision and visual elements in the entity tree.

fixed. 1c4f59c

**Comment by iche033** [comment]
> Can the ModelEditor not be a plugin, but instead be built into the component inspector?

Merged Model Editor plugin into Component Inspector. 0ecc731

**Comment by nkoenig** [comment]
Adding a link to a model doesn't change the entity tree (I can't see the light in the entity tree). Is that expected?

**Comment by iche033** [comment]
> Adding a link to a model doesn't change the entity tree (I can't see the light in the entity tree). Is that expected?

should be fixed in abb667d

**Comment by nkoenig** [comment]
Retargeting this to a `model_editor` branch. The `model_editor` branch can serve as model editor feature release branch.

**Review by nkoenig — APPROVED** [review]

**Pull request merged**
