### PR TITLE
Add Ubuntu Jammy CI

### PR DESCRIPTION
**Pull request by chapulina**
# 🎉 New feature

* Part of https://github.com/ignition-tooling/release-tools/issues/566

## Summary

~~I'm debugging Gazebo on Jammy from source and the changes in `packages.apt` were needed to install the correct dependencies, so I went ahead and opened the PR.~~

This is ready for review!

## Test it

~~Eventually Jammy CI should come back green.~~

Jammy CI comes back green sometimes, but it's flaky other times. Just like Bionic and Focal.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by chapulina** [comment]
Ouch, python 3.10 hits us, @j-rivero . Not sure you've seen this yet

```
  The following packages have unmet dependencies:
   python3-ignition-math6 : Depends: python3 (< 3.10) but 3.10.1-0ubuntu2 is to be installed
  E: Unable to correct problems, you have held broken packages.
```

**Comment by j-rivero** [comment]
> Ouch, python 3.10 hits us, @j-rivero . Not sure you've seen this yet
> 
> ```
>   The following packages have unmet dependencies:
>    python3-ignition-math6 : Depends: python3 (< 3.10) but 3.10.1-0ubuntu2 is to be installed
>   E: Unable to correct problems, you have held broken packages.
> ```

I did not see it. I'll fix it.

**Comment by j-rivero** [comment]
> I did not see it. I'll fix it.

I think that we were affected by the python 3.10 transition done in Jammy during the last month. Our ign-math6 package is coming from February and they changed the version. I'm going to bump the revision to just build the same source code again. That should make it.

**Comment by j-rivero** [comment]
> I think that we were affected by the python 3.10 transition done in Jammy during the last month. Our ign-math6 package is coming from February and they changed the version. I'm going to bump the revision to just build the same source code again. That should make it.

I've released 6.10.0-100 and that fixed the problem. CI is still failing, now because doxygen segfaults. I'm going to look at it.

**Comment by j-rivero** [comment]
Two things on my mind to stop using doxygen unconditionally:

 * Extend the `doxygen-enabled` input in the github action to avoid the installation of doxygen. You already proceed with that in https://github.com/ignition-tooling/action-ignition-ci/commit/17c5affe2603a4a1f0f85e98e16039faed64cd47. Sounds reasonable to me.
 * Why is ign-gazebo unconditionally running the doc generation in standard: cmake && make? Should it be out of the default target and only being run with `make doc`? 

For the second, a simple patch could be enough:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 13443e62..6ac33f1a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -225,26 +225,26 @@ endif()
 configure_file(${CMAKE_SOURCE_DIR}/api.md.in ${CMAKE_BINARY_DIR}/api.md)
 configure_file(${CMAKE_SOURCE_DIR}/tutorials.md.in ${CMAKE_BINARY_DIR}/tutorials.md)
 
-# disable doxygen on macOS due to issues with doxygen 1.9.0
-# there is an unreleased fix; revert this when 1.9.1 is released
-# https://github.com/ignitionrobotics/ign-gazebo/issues/520
-if (NOT APPLE)
-  ign_create_docs(
-    API_MAINPAGE_MD "${CMAKE_BINARY_DIR}/api.md"
-    TUTORIALS_MAINPAGE_MD "${CMAKE_BINARY_DIR}/tutorials.md"
-    ADDITIONAL_INPUT_DIRS "${CMAKE_SOURCE_DIR}/src/systems ${CMAKE_SOURCE_DIR}/src/gui/plugins"
-    IMAGE_PATH_DIRS "${CMAKE_SOURCE_DIR}/tutorials/files"
-    TAGFILES
-     "${IGNITION-MATH_DOXYGEN_TAGFILE} = ${IGNITION-MATH_API_URL}"
-     "${IGNITION-MSGS_DOXYGEN_TAGFILE} = ${IGNITION-MSGS_API_URL}"
-     "${IGNITION-PHYSICS_DOXYGEN_TAGFILE} = ${IGNITION-PHYSICS_API_URL}"
-     "${IGNITION-PLUGIN_DOXYGEN_TAGFILE} = ${IGNITION-PLUGIN_API_URL}"
-     "${IGNITION-TRANSPORT_DOXYGEN_TAGFILE} = ${IGNITION-TRANSPORT_API_URL}"
-     "${IGNITION-SENSORS_DOXYGEN_TAGFILE} = ${IGNITION-SENSORS_API_URL}"
-     "${IGNITION-COMMON_DOXYGEN_TAGFILE} = ${IGNITION-COMMON_API_URL}"
-  )
-endif()
-
 if(TARGET doc)
+  # disable doxygen on macOS due to issues with doxygen 1.9.0
+  # there is an unreleased fix; revert this when 1.9.1 is released
+  # https://github.com/ignitionrobotics/ign-gazebo/issues/520
+  if (NOT APPLE)
+    ign_create_docs(
+      API_MAINPAGE_MD "${CMAKE_BINARY_DIR}/api.md"
+      TUTORIALS_MAINPAGE_MD "${CMAKE_BINARY_DIR}/tutorials.md"
+      ADDITIONAL_INPUT_DIRS "${CMAKE_SOURCE_DIR}/src/systems ${CMAKE_SOURCE_DIR}/src/gui/plugins"
+      IMAGE_PATH_DIRS "${CMAKE_SOURCE_DIR}/tutorials/files"
+      TAGFILES
+       "${IGNITION-MATH_DOXYGEN_TAGFILE} = ${IGNITION-MATH_API_URL}"
+       "${IGNITION-MSGS_DOXYGEN_TAGFILE} = ${IGNITION-MSGS_API_URL}"
+       "${IGNITION-PHYSICS_DOXYGEN_TAGFILE} = ${IGNITION-PHYSICS_API_URL}"
+       "${IGNITION-PLUGIN_DOXYGEN_TAGFILE} = ${IGNITION-PLUGIN_API_URL}"
+       "${IGNITION-TRANSPORT_DOXYGEN_TAGFILE} = ${IGNITION-TRANSPORT_API_URL}"
+       "${IGNITION-SENSORS_DOXYGEN_TAGFILE} = ${IGNITION-SENSORS_API_URL}"
+       "${IGNITION-COMMON_DOXYGEN_TAGFILE} = ${IGNITION-COMMON_API_URL}"
+    )
+  endif()
+
   file(COPY ${CMAKE_SOURCE_DIR}/tutorials/files/ DESTINATION ${CMAKE_BINARY_DIR}/doxygen/html/files/)
 endif()

```

**Comment by chapulina** [comment]
Good news is that CI for Jammy is as good as Bionic and Focal now 🙂 A bit flaky 🙃

**Comment by mjcarroll** [comment]
> Why is ign-gazebo unconditionally running the doc generation in standard: cmake && make? Should it be out of the default target and only being run with make doc?

I'm pretty sure that all of our packages do, which is why I added this PR previously: https://github.com/ignitionrobotics/ign-cmake/pull/144

**Comment by mjcarroll** [comment]
We add the `doc` target to `ALL` here: https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/IgnCreateDocs.cmake#L179-L186

**Comment by chapulina** [comment]
Ah I didn't remember that option, @mjcarroll . Maybe we can just use that on the action then. That should be easier than changing `ign-cmake`

**Comment by j-rivero** [comment]
> We add the `doc` target to `ALL` here: https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/cmake/IgnCreateDocs.cmake#L179-L186

Ah thanks for the reminder. It could be somehow an intrusive change, maybe we target it on by default on ign-cmake3 but with that feature in place we call it ready to be used with ign-cmake2 like in this case.

> Ah I didn't remember that option, @mjcarroll . Maybe we can just use that on the action then. That should be easier than changing `ign-cmake`

+1 .

**Comment by chapulina** [comment]
@j-rivero , isn't [4e36f6e](https://github.com/ignitionrobotics/ign-gazebo/pull/1418/commits/4e36f6e004c13b38cde939b9be667c402c9ceac8) redundant as of https://github.com/ignition-tooling/action-ignition-ci/pull/51?

**Comment by j-rivero** [comment]
> @j-rivero , isn't [4e36f6e](https://github.com/ignitionrobotics/ign-gazebo/pull/1418/commits/4e36f6e004c13b38cde939b9be667c402c9ceac8) redundant as of [ignition-tooling/action-ignition-ci#51](https://github.com/ignition-tooling/action-ignition-ci/pull/51)?

It is. Both are correct I would say.

**Review by j-rivero — APPROVED** [review]

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-releases-2022-04-27-fortress-citadel/1389/1

**Pull request merged**
