### PR TITLE
5 ➡️ 6 (main)

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `ign-gazebo5` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-gazebo/compare/main...ign-gazebo5

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by jennuine** [comment]
On Ubuntu Focal, `ign gazebo -v 4 lights.sdf` isn't working as expected. When I use the sliders to change the colors of the lights in the component inspector nothing happens. Also, when I transform an object then try to interact with the lights again I can't. The same is happening in `main` as well (after applying this fix https://github.com/ignitionrobotics/ign-gazebo/pull/1018). This could be related to https://github.com/ignitionrobotics/ign-rendering/issues/402

Peek 2021-09-09 17-07

**Comment by jennuine** [comment]
https://github.com/ignitionrobotics/ign-rendering/issues/402 turned out not to be the issue. I'm still having the same issues with lights but it's also happening in main so I've ticketed an issue: https://github.com/ignitionrobotics/ign-gazebo/issues/1022

I believe I was not able to interact with the lights after transforming an object because the tool was still in transform mode. When I'm back in select mode I'm able to select the light entities again.

There are failing tests from `SdfGenerator_TEST.cc` should they be addressed in this PR?

**Comment by chapulina** [comment]
> I believe I was not able to interact with the lights after transforming an object because the tool was still in transform mode. When I'm back in select mode I'm able to select the light entities again.

Great detective work!

> There are failing tests from SdfGenerator_TEST.cc should they be addressed in this PR?

I've noticed these new test failures on `main` too, but haven't looked into it: https://build.osrfoundation.org/job/ignition_gazebo-ci-main-bionic-amd64/75/

**Comment by azeey** [comment]
> > There are failing tests from SdfGenerator_TEST.cc should they be addressed in this PR?
> 
> I've noticed these new test failures on `main` too, but haven't looked into it: https://build.osrfoundation.org/job/ignition_gazebo-ci-main-bionic-amd64/75/

Should be fixed by https://github.com/ignitionrobotics/ign-gazebo/pull/1023

**Review by jennuine — APPROVED** [review]

**Pull request merged**
