### PR TITLE
Dome version update

### PR DESCRIPTION
**Pull request by nkoenig**
This updates required versions for Dome.

### CODE REVIEW

**Comment by chapulina** [comment]
This requires:

* https://github.com/ignitionrobotics/ign-sensors/pull/31
* And `ign-sensors4` nightly release with :point_up: 
* A `homebrew-simulation` commit update

**Comment by j-rivero** [comment]
> This requires:

we might need to update to ign-physics3 before merging

```
2020-07-29T15:57:55.0423009Z  libignition-physics2-dev : Depends: libignition-physics2-dartsim-dev but it is not going to be installed
2020-07-29T15:57:55.0423472Z                             Depends: libignition-physics2-sdf-dev but it is not going to be installed
2020-07-29T15:57:55.0423965Z  libsdformat10-dev : Depends: libsdformat10 (= 10.0.0~pre1+nightly+git20200728+1r0f926078fd82ff34087f29350c387f999ac8a50d-1~bionic) but it is not going to be installed
2020-07-29T15:57:55.0542525Z E: Unable to correct problems, you have held broken packages.
```

**Comment by j-rivero** [comment]
> we might need to update to ign-physics3 before merging

physics3 problem is solved. I just add support for bionic in fuel-tools5, waiting in Jenkins to be built, that should make github actions happy (pending on X support for tests or disable them).

**Comment by j-rivero** [comment]
action is failing for tests:

```
2020-07-30T19:24:32.6186403Z The following tests FAILED:
2020-07-30T19:24:32.6186676Z 	 23 - UNIT_Server_TEST (Failed)
2020-07-30T19:24:32.6186953Z 	 39 - INTEGRATION_air_pressure_system (Failed)
2020-07-30T19:24:32.6187228Z 	 41 - INTEGRATION_altimeter_system (SEGFAULT)
2020-07-30T19:24:32.6187564Z 	 43 - INTEGRATION_apply_joint_force_system (SEGFAULT)
2020-07-30T19:24:32.6187855Z 	 45 - INTEGRATION_battery_plugin (SEGFAULT)
2020-07-30T19:24:32.6188119Z 	 47 - INTEGRATION_breadcrumbs (Failed)
2020-07-30T19:24:32.6188390Z 	 51 - INTEGRATION_contact_system (Failed)
2020-07-30T19:24:32.6188664Z 	 53 - INTEGRATION_detachable_joint (Failed)
2020-07-30T19:24:32.6188937Z 	 55 - INTEGRATION_diff_drive_system (Failed)
2020-07-30T19:24:32.6189205Z 	 63 - INTEGRATION_examples_build (Failed)
2020-07-30T19:24:32.6189479Z 	 65 - INTEGRATION_follow_actor_system (Failed)
2020-07-30T19:24:32.6189735Z 	 67 - INTEGRATION_imu_system (SEGFAULT)
2020-07-30T19:24:32.6190020Z 	 69 - INTEGRATION_joint_controller_system (Failed)
2020-07-30T19:24:32.6190293Z 	 71 - INTEGRATION_lift_drag_system (Failed)
2020-07-30T19:24:32.6190571Z 	 79 - INTEGRATION_logical_camera_system (SEGFAULT)
2020-07-30T19:24:32.6190849Z 	 81 - INTEGRATION_magnetometer_system (SEGFAULT)
2020-07-30T19:24:32.6191124Z 	 85 - INTEGRATION_multicopter (SEGFAULT)
2020-07-30T19:24:32.6191399Z 	 87 - INTEGRATION_network_handshake (Failed)
2020-07-30T19:24:32.6191671Z 	 89 - INTEGRATION_performer_detector (Failed)
2020-07-30T19:24:32.6191943Z 	 91 - INTEGRATION_physics_system (SEGFAULT)
2020-07-30T19:24:32.6192219Z 	 95 - INTEGRATION_pose_publisher_system (Failed)
2020-07-30T19:24:32.6192485Z 	 97 - INTEGRATION_save_world (Failed)
2020-07-30T19:24:32.6192769Z 	 99 - INTEGRATION_scene_broadcaster_system (Failed)
2020-07-30T19:24:32.6193043Z 	105 - INTEGRATION_thermal_system (Failed)
2020-07-30T19:24:32.6193308Z 	107 - INTEGRATION_touch_plugin (Failed)
2020-07-30T19:24:32.6193583Z 	109 - INTEGRATION_triggered_publisher (Failed)
2020-07-30T19:24:32.6193855Z 	111 - INTEGRATION_user_commands (SEGFAULT)
2020-07-30T19:24:32.6194108Z 	113 - INTEGRATION_log_system (SEGFAULT)
2020-07-30T19:24:32.6194375Z 	115 - INTEGRATION_wind_effects (Failed)
2020-07-30T19:24:32.6194640Z 	119 - PERFORMANCE_level_manager (Failed)
```
@chapulina do we want to add xfvb support or just disable them in github actions? There are many errors coming from the fact of not being able to find plugins.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
> @chapulina do we want to add xfvb support or just disable them in github actions? There are many errors coming from the fact of not being able to find plugins.

testing it here 1734811

**Comment by j-rivero** [comment]
Looking into the failures for linux and brew.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
the fail on Linux is expected (docker cache not being updated correctly). I'm testing a permanent fix in next builds.

**Comment by j-rivero** [comment]
wew! finally get all the CI mechanisms working. Merging and going for launch.

**Pull request merged**
