### PR TITLE
Add light intensity field to ComponentInspector

### LINKED ISSUE #637: Allow to modify light intensity with the ComponentInspector - ign-gazebo5
## Desired behavior

When the Light editor is forward ported to ign-gazebo5 we should allow to modify light intensity with the ComponentInspector in ign-gazebo5 like the other field (specular, diffuse, attenuations, ... )

## Implementation suggestion

Refer to this PR https://github.com/ignitionrobotics/ign-gazebo/pull/482 for more context

### PR DESCRIPTION
**Pull request by atharva-18**
Signed-off-by: Atharva Pusalkar <atharvapusalkar18@gmail.com>

# 🎉 New feature

Closes #637 

## Summary
I have added light intensity field to the ComponentInspector. Changes were also made to `RenderUtil.cc` and `UserCommands.cc` to set the light intensity value.
Here's a demo:
light_intensity

## Test it
You can test the feature by running `ign gazebo examples/worlds/lights.sdf`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
thank you for the contribution!

Do you mind to add the intensity to the Plotting plugin ?

**Comment by atharva-18** [comment]
@ahcorde Added in [`b145cb4`](https://github.com/ignitionrobotics/ign-gazebo/pull/670/commits/b145cb4dde5ef9e5dc0eeffa5fae4dd799350e2e)!

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Review by ahcorde — APPROVED** [review]
Waiting CI

**Review by chapulina — APPROVED** [review]
Thanks for the PR!

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by atharva-18** [comment]
These tests are failing on macOS catalina:
```
The following tests FAILED:
	 83 - INTEGRATION_imu_system (SEGFAULT)
	113 - INTEGRATION_multiple_servers (SEGFAULT)
	139 - INTEGRATION_user_commands (SEGFAULT)
```

**Comment by ahcorde** [comment]
Thank you for the contribution @atharva-18

**Pull request merged**
