### PR TITLE
3 to 4

### PR DESCRIPTION
**Pull request by adlarkin**
# ➡️ Forward port

Port `ign-gazebo3` to `ign-gazebo4`

Branch comparison: https://github.com/ignitionrobotics/ign-gazebo/compare/ign-gazebo4...ign-gazebo3

---

I had to resolve a few merge conflicts. I believe that we will also need an `ign-gui4` release in order to support https://github.com/ignitionrobotics/ign-gazebo/pull/904, which is part of this forward-port.

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
LGTM when CI is happy

**Comment by adlarkin** [comment]
It looks like macOS hasn't picked up on the new GUI release: https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/6141/consoleFull#18361520546ea37b8d-a6d4-40ae-8431-d90c018842af

However, the bottle has been built (I think): https://github.com/osrf/homebrew-simulation/pull/1541

Is there a way to verify that macOS has picked up the new GUI release?

**Comment by adlarkin** [comment]
Now that the `ign-gui` release is out, I have updated `CMakeLists.txt` to require `ign-gui 4.5.0`.

**Comment by adlarkin** [comment]
macOS is building now. The [INTEGRATION_user_commands](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/6142/testReport/(root)/INTEGRATION_user_commands/test_ran/) test failed again, but it has failed for the past 19 builds, so I don't think it's related to this PR. I'll go ahead and merge this.

**Pull request merged**
