### PR TITLE
5 ➡️ 6

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `ign-gazebo5` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-gazebo/compare/main...ign-gazebo5

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by chapulina** [comment]
The homebrew build should be fixed by https://github.com/osrf/homebrew-simulation/pull/1456.

I think the rest looks good!

**Comment by scpeters** [comment]
> The homebrew build should be fixed by [osrf/homebrew-simulation#1456](https://github.com/osrf/homebrew-simulation/pull/1456).
> 
> I think the rest looks good!

https://github.com/osrf/homebrew-simulation/pull/1456 has been merged, so I restarted the homebrew build (after wiping out the workspace)

**Comment by scpeters** [comment]
> > The homebrew build should be fixed by [osrf/homebrew-simulation#1456](https://github.com/osrf/homebrew-simulation/pull/1456).
> > I think the rest looks good!
> 
> [osrf/homebrew-simulation#1456](https://github.com/osrf/homebrew-simulation/pull/1456) has been merged, so I restarted the homebrew build (after wiping out the workspace)

homebrew build is still failing because `sdformat12` formula is out of date. I've opened https://github.com/ignitionrobotics/ign-gazebo/pull/811 as a potential solution

**Comment by chapulina** [comment]
> homebrew build is still failing because sdformat12 formula is out of date. I've opened osrf/homebrew-simulation#1459 as a potential solution

Same for `ign-physics5` to fix the `velocity_control` test: https://github.com/osrf/homebrew-simulation/pull/1460

**Comment by scpeters** [comment]
> > homebrew build is still failing because sdformat12 formula is out of date. I've opened [osrf/homebrew-simulation#1459](https://github.com/osrf/homebrew-simulation/pull/1459) as a potential solution
> 
> Same for `ign-physics5` to fix the `velocity_control` test: [osrf/homebrew-simulation#1460](https://github.com/osrf/homebrew-simulation/pull/1460)

that has been merged so I retried the home-brew jenkins build to see if the velocity control test is fixed:

* [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/5645/) https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/5645/

**Comment by scpeters** [comment]
the `PERFORMANCE_level_manager` test failed in both bionic GitHub actions runs, so I filed #826 to track it

I think any other test failures are flaky. I'm going to merge

**Pull request merged**
