### PR TITLE
Documentation Error

### PR DESCRIPTION
**Pull request by harshmahesheka**

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@harshmahesheka can you [sign](https://github.com/ignitionrobotics/ign-gazebo/pull/1285/checks?check_run_id=4785708969) the commit ?

**Comment by harshmahesheka** [comment]
Yeah, sure.

**Comment by harshmahesheka** [comment]
> @harshmahesheka can you [sign](https://github.com/ignitionrobotics/ign-gazebo/pull/1285/checks?check_run_id=4785708969) the commit ?
Yeah,sure

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1

**Pull request merged**
