### PR TITLE
cessna plugin added [wip]

### PR DESCRIPTION
**Pull request by addy1997**
## Summary
I have added the Cessna plugin. This is a model plugin used to control the Cessna C-172 airplane.

Screenshot 2021-07-09 at 17 05 38

## Test it
An example world file can be found [here](https://github.com/ignitionrobotics/ign-gazebo/blob/4c8f6be65c8493005e5280753bea0d18d709d03f/examples/worlds/cessna.sdf).

`ign gazebo -r cessna.sdf`

Note: Mesh files can be downloaded from [ignition fuel](https://app.ignitionrobotics.org/chapulina/fuel/models/Cessna%20C-172).

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

### CODE REVIEW

**Comment by ahcorde** [comment]
Hi @addy1997, 

thank you for your contribution, I highly suggest you to finish this PR https://github.com/ignitionrobotics/ign-gazebo/pull/845 before open new ones. Anyhow most of the comments that I made in the gimbal PR also applies here.

**Comment by addy1997** [comment]
> Hi @addy1997,
> 
> thank you for your contribution, I highly suggest you to finish this PR #845 before open new ones. Anyhow most of the comments that I made in the gimbal PR also applies here.

Sir, unlike #845, I have added the world file to test this plugin. I will add the test file for further validation.

**Comment by ahcorde** [comment]
This plugin should not live in `examples/plugin`, you should move it to `src/system` and you should add a test to check that the plugin is working properly.

Add a new test requires:
  - add a similar sdf file to `test/world/`, you can remove lights and other thing that not relevant for testing the functionality.
  - write the test, You can take a look `test/integration/

**Comment by ahcorde** [comment]
> Sir, unlike #845, I have added the world file to test this plugin. I will add the test file for further validation.

Just to clarify the differences between test files in `tests/world/ and `examples/world`

 - `test/world` These files should be loaded by Unit tests, such as the ones located in `test/integration`. These files will help us to check that the code that we write is working properly, this is done in every new PR to check that new additions/modifications are not affecting the current features of ignition.
 - `test/world`. These files are loaded by user to test Ignition functionatily.

Each new system plugin must add both.

**Comment by addy1997** [comment]
> > Sir, unlike #845, I have added the world file to test this plugin. I will add the test file for further validation.
> 
> Just to clarify the differences between test files in `tests/world/ and `examples/world`
> 
>     * `test/world` These files should be loaded by Unit tests, such as the ones located in `test/integration`. These files will help us to check that the code that we write is working properly, this is done in every new PR to check that new additions/modifications are not affecting the current features of ignition.
> 
>     * `test/world`. These files are loaded by user to test Ignition functionatily.
> 
> 
> Each new system plugin must add both.

On it sir.

**Comment by chapulina** [comment]
Hi @addy1997 , as discussed, let's first iterate on #845 before you open new pull requests. This way you should be able to learn how to contribute and the iteration on this and other future PRs will be much easier :wink: Please focus on that one, I'm closing this one until that's merged.

---

As a side note, I think that this plugin should be renamed as we migrate it to Ignition so it isn't too specific to the Cessna model. I recommend renaming it to something like `FixedWingController` so that it can be extended to other models too.

Also, the next time you open the PR, be sure to include a video of the plane flying so that we can see it works.

**Pull request closed without merging**
