### PR TITLE
Disable more tests on Windows

### PR DESCRIPTION
**Pull request by chapulina**
# 🦟 Bug fix

* Follow up to #1205 after it was forward-ported on https://github.com/ignitionrobotics/ign-gazebo/pull/1277
* Part of https://github.com/ignitionrobotics/ign-gazebo/issues/1175

## Summary

This addresses tests that are new on Fortress.

The goal is to have zero failing tests on Windows, this way we know if we're introducing new failures.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by Blast545 — APPROVED** [review]
LGTM

**Comment by Blast545** [comment]
Although CI result has still some failing tests, did you take as the list of tests to disable the one I had in the original issue? or did you removed the last ones from CI? @chapulina

**Comment by chapulina** [comment]
> Although CI result has still some failing tests, did you take as the list of tests to disable the one I had in the original issue? or did you removed the last ones from CI?

I was tackling the ones I saw failing on #1277, let me do the rest now

**Comment by chapulina** [comment]
Ok, I tackled other recent tests in 6ace1df.

I think we should wait for an `ign-common` release (https://github.com/ignitionrobotics/ign-common/pull/288), which I hope will make the `ElementUpdateFixture.WorldWithModelsIncludedWithInvalidUris` test pass on all platforms.

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-24-citadel-edifice-fortress/1241/1

**Pull request merged**
