### PR TITLE
Removed duplicated code with rendering::sceneFromFirstRenderEngine

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# Enhancement

## Summary

Related to this PR in ignition-renderin https://github.com/ignitionrobotics/ign-rendering/pull/320#event-4749407284. It uses the helper function rendering::sceneFromFirstRenderEngine to get the first scene that can be found in any rendering engine.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Review by mjcarroll — APPROVED** [review]

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Pull request merged**
