### PR TITLE
Eliminates std::filesystem usage in utils.cc

### PR DESCRIPTION
**Pull request by arjo129**
# 🦟 Bug fix

Fixes #<NUMBER>

## Summary
Depends on https://github.com/ignitionrobotics/ign-common/pull/312

See https://github.com/ignition-tooling/release-tools/issues/639

Basically, this removes the dependency on `std::filesystem` in  ign-gazebo as its been causing issues when binaries are produced by different compiler versions. This current version makes sure that we keep all `std::filesystem` code in` ign-common`.

Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by nkoenig — APPROVED** [review]

**Comment by nkoenig** [comment]
I think you can target this to ign-gazebo6, and the same goes for the ign-common PR.

**Comment by mjcarroll** [comment]
I guess we are going to have to do an `ign-common6` prerelease for this?

**Comment by chapulina** [comment]
@osrf-jenkins run tests again

> I guess we are going to have to do an ign-common6 prerelease for this?

This is targeting unstable branches, so we should be able to use the nightlies

**Review by chapulina — APPROVED** [review]
LGTM with happy CI

**Pull request merged**
