### PR TITLE
Fix ColladaExporter submesh index bug

### LINKED ISSUE #761: ColladaExporter submesh index bug
## Description
* Expected behavior: 

Running this command would show the complete world meshes. Test world taken from [finals_practice_01.sdf](https://github.com/osrf/subt/blob/master/subt_ign/worlds/finals_practice_01.sdf)
```ign gazebo -v 3 -s -r --iterations 1 ros_ws/src/subt/subt_ign/worlds/finals_practice_01.sdf```

* Actual behavior: 
It doesn't export properly

image

### PR DESCRIPTION
**Pull request by Blast545**
# 🦟 Bug fix

Fixes #761

## Summary

The fix IMO is straightforward, use the iteration index to include properly the missing submeshes to the exported SubMeshes array.

I closed the previous PR because I had to rebase in top of ign-gazebo5.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

### CODE REVIEW

**Comment by chapulina** [comment]
Would it be possible to add a test with submeshes to https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/test/integration/collada_world_exporter.cc ?

**Comment by Blast545** [comment]
@chapulina Sure! I'll add a test there for submeshes with this PR

**Comment by Blast545** [comment]
@chapulina I added a test for sub-meshes as you asked me, the model from fuel that started the issue. 

Please note though that the test only checks if there's an output, and the issue addressed with this PR was silently failing as the exported result was incorrect.

**Comment by luca-della-vedova** [comment]
I can confirm that I had the same issue and went through fixing it and... Wrote the same fix locally, then when opening a PR I saw this branch :sweat_smile:

**Comment by chapulina** [comment]
> The test also seems to add quite a lot of binaries

Agreed, ideally we'd use a model as simple as possible, with just enough meshes and textures to test the functionality.

**Comment by Blast545** [comment]
@chapulina @luca-della-vedova Thanks for your comments, I added a simpler test case taken from `ign-common` tests.

**Comment by nkoenig** [comment]
Is the `mesh_with_submeshes.dae` needed?

**Comment by Blast545** [comment]
@nkoenig I addressed your comment with `f1596eb`. Actually the extra file was the `box.dae`, the intented file to test was the one with submeshes :disappointed_relieved:. Thanks!

**Review by nkoenig — APPROVED** [review]

**Comment by Blast545** [comment]
Force-pushed to rebase on top of updated ign-gazebo5, commits weren't changed.

**Review by chapulina — APPROVED** [review]

**Pull request merged**
