### PR TITLE
Add functionalities for optical tactile plugin

### PR DESCRIPTION
**Pull request by mcres**
This PR is a change of target from [this PR in my fork](https://github.com/mcres/ign-gazebo/pull/1).

This PR adds the following:

* Service for enabling/disabling the plugin
* Topic for the normal forces computed
* Test
* Visualize the contacts from the contact sensor

### CODE REVIEW

**Comment by mcres** [comment]
CC @mabelzhang

**Comment by mabelzhang** [comment]
Will review after #229 is merged, to reduce the diffs here.

**Comment by chapulina** [comment]
#229 is in, moving this to "In Review"!

**Comment by chapulina** [comment]
> then will update feature branch to reduce the diffs here.

I just noticed that this PR isn't targeting `ign-gazebo4`. Can it be retargeted and rebased, @mabelzhang ?

**Review by mabelzhang — COMMENTED** [review]
I reviewed most of the files and pushed some changes, mostly for style.
Only file I still need to review is the tests.

**Comment by mabelzhang** [comment]
I'm saving the Mac CI error message from the new test, in case the link dies before I come back to fix it.
Might need to add some directives for Mac.
```
149: [ RUN      ] OpticalTactilePluginTest.ForcesOnPlane
149: [Err] [Ogre2RenderEngine.cc:436] Unable to find Ogre Plugin[/usr/local/opt/ogre2.1/lib/OGRE-2.1/RenderSystem_GL3Plus]. Rendering will not be possible.Make sure you have installed OGRE properly.
149: [Err] [Ogre2RenderEngine.cc:739]  Unable to create the rendering window
```

**Comment by chapulina** [comment]
I pushed some tweaks in 50f4250. This is working well for me! We just need to check the macOS tests. They're currently failing for a different reason, which will be fixed by #792 .

**Comment by chapulina** [comment]
The macOS tests are failing to load Ogre just like in https://github.com/ignitionrobotics/ign-sensors/issues/66 and https://github.com/ignitionrobotics/ign-gui/issues/145, so I disabled the test for macOS on 4ffad4d

**Review by mabelzhang — APPROVED** [review]
Approving because Mac failing tests were my only concern

**Review by chapulina — APPROVED** [review]
Good to go! :rocket:

**Pull request merged**
