### PR TITLE
Code for actor walking in circular path

### PR DESCRIPTION
**Pull request by addy1997**
I have added the code for the Actor to move in the circle.

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
Thank you for the pull request, @addy1997 . Did you mean to include all the other worlds too? I recommend creating separate branches for each feature so you can open pull requests for them separately.

Similar to #645 , how do you feel about uploading `Actor_circle_path.sdf` to Fuel? Once you've uploaded a lot of these worlds, I suggest you post about them on https://community.gazebosim.org/ so more people take a look at them!

**Comment by addy1997** [comment]
@chapulina Nope, I didn't mean to include all the worlds. This was just for the actor's circular path. Would uploading a single actor world file make the entire repo bulky?

**Comment by chapulina** [comment]
> Would uploading a single actor world file make the entire repo bulky?

Got it. One world file is not that large, but in general, we're trying not to add new worlds for now unless they're demonstrating some new functionality. And eventually we'll move all of them to Fuel.

**Comment by addy1997** [comment]
> > Would uploading a single actor world file make the entire repo bulky?
> 
> Got it. One world file is not that large, but in general, we're trying not to add new worlds for now unless they're demonstrating some new functionality. And eventually, we'll move all of them to Fuel.

Thanks for that. I have uploaded the world model with the proper format and thumbnails. [Link](https://app.ignitionrobotics.org/Gambit/fuel/worlds/actor%20walk%20circle)

**Pull request closed without merging**
