### PR TITLE
3 ➡️ 4

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by chapulina** [comment]
Test failures:

* `UNIT_Conversions_TEST`: fixed by https://github.com/ignitionrobotics/ign-gazebo/pull/288
* `INTEGRATION_components`: fixed by https://github.com/ignitionrobotics/ign-gazebo/pull/288
* `INTEGRATION_breadcrumbs`: possibly introduced by this PR, I'd like to see a new macOS run to check.

**Comment by chapulina** [comment]
@osrf-jenkins run tests now

**Comment by chapulina** [comment]
Mac warnings and breadcrumbs test failures will fixed when merging #327 forward.

**Review by JShep1 — APPROVED** [review]
LGTM, builds and runs successfully!

**Pull request merged**
