### PR TITLE
Fix WindEffects Plugin bug, not configuring new links

### LINKED ISSUE #843: WindEffects plugin not adding wind components to links added after first PreUpdate
## Environment
* OS Version: Ubuntu focal
* Source installation
 
## Details
As the title says, elements added after the first PreUpdate iteration in the WindEffects plugin do not configure new links added to the simulation environment.

This line of code: https://github.com/ignitionrobotics/ign-gazebo/blob/fb973bd748a051566eedc4e1e112268ae8cd6909/src/systems/wind_effects/WindEffects.cc#L555

Makes an incorrect assumption that all the links are available when the simulation starts, and this might not always be the case.

I'll open a PR addressing this with code used for the buoyancy plugin.

### PR DESCRIPTION
**Pull request by Blast545**
# 🦟 Bug fix

Fixes #843 

## Summary
Fixes tagged issue. I'm not sure how to test this bug fix, can I get some advice about how to this fix? I imagine the test would be something like:

1. Create server
2. Add links with wind
3. Run sim iteration
4. Check if wind was added
5. Add more links with wind
6. Check if wind was added to the new ones.

Let me know your thoughts.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Review by azeey — COMMENTED** [review]
This looks good! For testing, I recommend using the user-commands system to spawn a model as done in this example: https://github.com/ignitionrobotics/ign-gazebo/blob/80379fb4515c246a6b0bc2ee078755eb83230655/test/integration/touch_plugin.cc#L233

**Comment by Blast545** [comment]
@azeey I followed your advice, let me know what you think :)

**Comment by chapulina** [comment]
@Blast545 , can this be moved to "In review"? Also I noticed you retargeted to `ign-gazebo3` then back, are you still working on retargeting?

**Comment by Blast545** [comment]
@chapulina Yes! I'm re-targeting it. I thought using the web GUI was enough, and when I saw the conflicts I realized I'll have to do it manually :laughing:

**Comment by Blast545** [comment]
@azeey CI all green (except codecov) PTAL, I think is ready to merge :D

**Review by azeey — APPROVED** [review]
Thanks!

**Pull request merged**
