### PR TITLE
Using math::SpeedLimiter on the ackermann_steering controller.

### PR DESCRIPTION
**Pull request by LolaSegura**
Signed-off-by: LolaSegura lsegura@ekumenlabs.com

## Summary
This replace the ackermann_steering controller speed limiter class for the one implemented in ignition math. Part of #810. 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers
🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by caguero — APPROVED** [review]
It looks good to me!

**Review by caguero — COMMENTED** [review]
Nit: I think we don't need the `#include <limits>` anymore.

**Comment by LolaSegura** [comment]
> Nit: I think we don't need the #include <limits> anymore.

@caguero  you are right, I deleted it. Thanks for catching that.

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
looks good to me; I think the only test failures are flaky

**Pull request merged**
