### PR TITLE
Add thermal camera test for object temperature below 0

### PR DESCRIPTION
**Pull request by adlarkin**
Requires https://github.com/ignitionrobotics/ign-rendering/pull/243.

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example world and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by adlarkin** [comment]
Marking this as ready for review, thanks to https://github.com/ignitionrobotics/ign-rendering/pull/243#issuecomment-777019583 which makes this test pass.

**Comment by adlarkin** [comment]
I'm holding off on merging this PR so that it doesn't delay the upcoming `ign-gazebo` release. I'm marking this as a draft for now, but will re-open it once the `ign-gazebo` release is complete.

**Comment by adlarkin** [comment]
@iche033 I believe this is ready for review. Tests are currently failing in CI because we need to merge https://github.com/ignitionrobotics/ign-rendering/pull/243 and make an `ign-rendering` release (the tests pass locally for me if I build `ign-gazebo` and `ign-rendering` from source).

**Review by iche033 — COMMENTED** [review]
changes look good to me. Need to wait for an ign-rendering4 release

**Comment by adlarkin** [comment]
> changes look good to me. Need to wait for an ign-rendering4 release

Release has been made. I have updated the `CMakeLists.txt` to reflect the updated dependency in https://github.com/ignitionrobotics/ign-gazebo/pull/621/commits/b7e44421a970ca7a4299e7c9020ec17865bb5b19

**Pull request merged**
