### PR TITLE
4 ➡️ 5

### PR DESCRIPTION
**Pull request by chapulina**
Forward-port `ign-gazebo4` to `main`

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
CI is failing. Do we need to depend on SDF 11?

**Comment by chapulina** [comment]
> CI is failing. Do we need to depend on SDF 11?

Yup, that was done on #549 , let's see how CI goes now

**Comment by chapulina** [comment]
This PR requires https://github.com/ignitionrobotics/ign-transport/pull/209

**Review by caguero — APPROVED** [review]

**Comment by chapulina** [comment]
Argh! I rushed and squashed by mistake :sob:

**Pull request merged**
