### PR TITLE
Fixed the selection of the visual in transform control

### PR DESCRIPTION
**Pull request by ahcorde**
I have the same issue described in this PR https://github.com/ignitionrobotics/ign-rendering/pull/221

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by nkoenig** [comment]
I think this breaks selecting a transform control arrow when an object is in front of the arrow.

**Comment by iche033** [comment]
could be related to https://github.com/ignitionrobotics/ign-gazebo/issues/147

**Comment by iche033** [comment]
I think it could be a transparency change that's been done in Dome (could be in ign-rendering)

**Comment by ahcorde** [comment]
closing this PR the issue can be fixed in ign-rendering https://github.com/ignitionrobotics/ign-rendering/pull/221

**Pull request closed without merging**
