### PR TITLE
🎈 5.1.0~pre1

### PR DESCRIPTION
**Pull request by chapulina**
# 🎈 Release

Preparation for 5.1.0~pre1 release.

Comparison to 5.0.0: https://github.com/ignitionrobotics/ign-gazebo/compare/ignition-gazebo5_5.0.0...ign-gazebo5

The current debs are crashing when trying to load poses from SDF (https://github.com/ignitionrobotics/ign-gazebo/issues/891). If it's an ABI issue, this pre-release may fix it.

See #885

## Checklist
- [x] Asked team if this is a good time for a release
- [x] There are no changes to be ported from the previous major version - there's always something, a big pass was done in #877
- [x] No PRs targeted at this major version are close to getting in - this release is already large enough that I don't think we need to wait for changes to come in
- [x] Bumped minor for new features, patch for bug fixes
- [x] Updated changelog
- [ ] Updated migration guide (as needed)
- [x] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): https://github.com/ignition-release/ign-gazebo5-release/pull/11

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]

**Comment by chapulina** [comment]
Oh I just remembered another issue with the release, all the new test failures related to wheel friction.

**Comment by adlarkin** [comment]
As we discussed offline, it seems like #891 is because of an ABI break in sdformat: https://github.com/osrf/sdformat/compare/sdformat11_11.1.0...sdf11

So, making a pre-release here won't resolve that, right? I think we need to update sdformat and make releases there?

**Comment by scpeters** [comment]
> As we discussed offline, it seems like #891 is because of an ABI break in sdformat: [osrf/sdformat@sdformat11_11.1.0...sdf11](https://github.com/osrf/sdformat/compare/sdformat11_11.1.0...sdf11)
> 
> So, making a pre-release here won't resolve that, right? I think we need to update sdformat and make releases there?

usually when there's an ABI change, you can fix it by rebuilding the downstream packages, so I think rebuilding ign-gazebo could help

**Comment by scpeters** [comment]
> > As we discussed offline, it seems like #891 is because of an ABI break in sdformat: [osrf/sdformat@sdformat11_11.1.0...sdf11](https://github.com/osrf/sdformat/compare/sdformat11_11.1.0...sdf11)
> > So, making a pre-release here won't resolve that, right? I think we need to update sdformat and make releases there?
> 
> usually when there's an ABI change, you can fix it by rebuilding the downstream packages, so I think rebuilding ign-gazebo could help

we might need to rebuild ignition-physics as well

**Comment by chapulina** [comment]
We decided to make a new SDFormat release reverting the ABI breaking changes. I'll hold this release until that's out so we don't build against the broken ABI. CC @azeey .

This will also give @scpeters some time to look into the friction changes.

**Comment by scpeters** [comment]
> We decided to make a new SDFormat release reverting the ABI breaking changes. I'll hold this release until that's out so we don't build against the broken ABI. CC @azeey .
> 
> This will also give @scpeters some time to look into the friction changes.

the test failures are already present on `ign-gazebo5`, and they are fixed in my local tests of https://github.com/ignitionrobotics/sdformat/pull/606. So I think they are related to the ABI break and should be fixed once we make a new libsdformat11 release

**Comment by chapulina** [comment]
> So I think they are related to the ABI break

Ohhhh I didn't think of that because the ABI break has been crashing Gazebo on startup for me. But now that you said it I can imagine that it may manifest in different ways on CI.

Let's wait for the new SDF release then :pray:

**Comment by chapulina** [comment]
I don't see new test failures :smile:

**Pull request merged**
