### PR TITLE
Bumps in garden: use ign-math7 and dependents

### PR DESCRIPTION
**Pull request by chapulina**
See https://github.com/ignition-tooling/release-tools/issues/574

### CODE REVIEW

**Review by caguero — APPROVED** [review]

**Comment by chapulina** [comment]
The `TriggeredPublisher` test failures seem to be caused by SDFormat:

```
173: [ RUN      ] TriggeredPublisherTest.EmptyInputEmptyOutput
173: [Msg] Loading SDF world file[/home/jenkins/workspace/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/ign-gazebo/test/worlds/triggered_publisher.sdf].
173: Error [Param.cc:768] Unknown parameter type[ignition.msgs.Boolean]
173: Exception [Param.cc:81] SDF ASSERTION                     
173: Invalid parameter
173: In function       : Param
173: Assert expression : this->dataPtr->ValueFromStringImpl( this->dataPtr->typeName, _default, this->dataPtr->defaultValue)
173: unknown file: Failure
173: Unknown C++ exception thrown in SetUp().
```

It may already be on `main`, but we can't trigger a test build because we're in the middle of the dependency bump.

**Comment by scpeters** [comment]
> The `TriggeredPublisher` test failures seem to be caused by SDFormat:
> 
> ```
> 173: [ RUN      ] TriggeredPublisherTest.EmptyInputEmptyOutput
> 173: [Msg] Loading SDF world file[/home/jenkins/workspace/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/ign-gazebo/test/worlds/triggered_publisher.sdf].
> 173: Error [Param.cc:768] Unknown parameter type[ignition.msgs.Boolean]
> 173: Exception [Param.cc:81] SDF ASSERTION                     
> 173: Invalid parameter
> 173: In function       : Param
> 173: Assert expression : this->dataPtr->ValueFromStringImpl( this->dataPtr->typeName, _default, this->dataPtr->defaultValue)
> 173: unknown file: Failure
> 173: Unknown C++ exception thrown in SetUp().
> ```
> 
> It may already be on `main`, but we can't trigger a test build because we're in the middle of the dependency bump.

Observations:

* The test failures happen on both Ubuntu and homebrew.
* I don't see these test failures on ign-gazebo6 using the latest stable release of `libsdformat12`:
    * [Build Status](https://build.osrfoundation.org/view/ign-fortress/job/ignition_gazebo-ci-ign-gazebo6-bionic-amd64/) https://build.osrfoundation.org/view/ign-fortress/job/ignition_gazebo-ci-ign-gazebo6-bionic-amd64/
* I've looked at some branch comparisons of sdformat and ign-gazebo and don't see any significant differences between `main` and the previous stable branch that indicate a cause of this problem
    * https://github.com/ignitionrobotics/sdformat/compare/main
    * https://github.com/ignitionrobotics/ign-gazebo/compare/main
* I do, however, see a substantial number of unreleased changes on `sdf12` that have not been tested by any of `ign-gazebo`'s Ubuntu or homebrew builds

I suggest a prerelease of `libsdformat12`

**Comment by scpeters** [comment]
> I suggest a prerelease of `libsdformat12`

and I think we should disable the triggered publisher tests so we can finish this merge

**Comment by scpeters** [comment]
I suspect https://github.com/ignitionrobotics/sdformat/pull/689 for the TriggeredPublisher test failures

**Comment by chapulina** [comment]
> I think we should disable the triggered publisher tests so we can finish this merge

Since `ign-gazebo` already has other failing / flaky tests, I think it's ok to leave those failing so we remember to address them quickly.

> I suggest a prerelease of libsdformat12

I can reproduce the failure locally on a Fortress workspace, so we don't need the pre-release to confirm the issue. Let me take a stab at it, hopefully it's an easy fix.

**Comment by scpeters** [comment]
> I suspect [ignitionrobotics/sdformat#689](https://github.com/ignitionrobotics/sdformat/pull/689) for the TriggeredPublisher test failures

I've commented https://github.com/ignitionrobotics/sdformat/pull/689/files#r776821783 on the line I believe to be causing the problem

**Comment by scpeters** [comment]
> > I think we should disable the triggered publisher tests so we can finish this merge
> 
> Since `ign-gazebo` already has other failing / flaky tests, I think it's ok to leave those failing so we remember to address them quickly.

the triggered publisher failures were the only problems with the following build:

* [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/7759/) https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/7759

I think it's worth disabling the builds before merging this rather than merging them if we know they will always be failing

> > I suggest a prerelease of libsdformat12
> 
> I can reproduce the failure locally on a Fortress workspace, so we don't need the pre-release to confirm the issue. Let me take a stab at it, hopefully it's an easy fix.

if not a prerelease, perhaps we could trigger some nightly builds of libsdformat12? I think it will be easier to confirm the fix if we have debs that we can use from CI builds. An alternative would be building an entire workspace from source from a specified `.repos` file like the ROS2 CI

**Comment by chapulina** [comment]
> I think it's worth disabling the builds before merging this rather than merging them if we know they will always be failing

Ok, disabling those tests, right? We'll just need another PR to re-enable them soon.

>  An alternative would be building an entire workspace from source from a specified .repos file like the ROS2 CI

Yeah we can do that with GitHub actions. I'm hoping to open a PR upstream soon with a band-aid  that we can test against `ign-gazebo`. Or are you saying we should test the current `sdf12` branch to confirm the issue?

**Comment by chapulina** [comment]
@scpeters , what do you think of not blocking this on the triggered publisher issue? I'd like to finish bumping `ign-launch` and `ign-garden` today. If you feel strongly about disabling the tests on this PR I can do that now, just let me know. The issue is coming from `ign-gazebo6`, so disabling them here only solves part of the issue.

>> An alternative would be building an entire workspace from source from a specified .repos file like the ROS2 CI
> Yeah we can do that with GitHub actions. 

* See #1266

**Comment by scpeters** [comment]
> @scpeters , what do you think of not blocking this on the triggered publisher issue? I'd like to finish bumping `ign-launch` and `ign-garden` today. If you feel strongly about disabling the tests on this PR I can do that now, just let me know. The issue is coming from `ign-gazebo6`, so disabling them here only solves part of the issue.
> 
> > > An alternative would be building an entire workspace from source from a specified .repos file like the ROS2 CI
> > > Yeah we can do that with GitHub actions.
> 
> * See [Build SDF from source to reproduce test failures #1266](https://github.com/ignitionrobotics/ign-gazebo/pull/1266)

yes we should disable the triggered publisher test

**Comment by chapulina** [comment]
> yes we should disable the triggered publisher test

Ok, disabled in faf7533

**Comment by scpeters** [comment]
> > yes we should disable the triggered publisher test
> 
> Ok, disabled in [faf7533](https://github.com/ignitionrobotics/ign-gazebo/commit/faf7533219a6dbc24ce385c0b0ff7d5ab55389a7)

to remind us to reenable the tests: https://github.com/ignitionrobotics/ign-gazebo/issues/1267

**Review by scpeters — APPROVED** [review]

**Comment by chapulina** [comment]
Merging this and its related infrastructure PRs:

* https://github.com/ignition-release/ign-gazebo7-release/pull/3
* https://github.com/osrf/homebrew-simulation/pull/1762
* https://github.com/ignition-tooling/gazebodistro/pull/70

**Pull request merged**
