### PR TITLE
Use uint64_t with gazebo-entity user dataa

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

Related with https://github.com/ignitionrobotics/ign-gazebo/issues/1378

## Summary

Use `uint64_t` with gazebo-entity user data

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by iche033 — COMMENTED** [review]
I think we'll need to add `uint64_t` to the `Variant` type in ign-rendering: https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering6/include/ignition/rendering/Node.hh#L45-L47

**Comment by ahcorde** [comment]
it's already on `main` https://github.com/ignitionrobotics/ign-rendering/blob/main/include/ignition/rendering/Node.hh#L45-L47

**Comment by iche033** [comment]
oh yeah missed that. 

changes look good. Not sure what's wrong with the ubuntu build. Just retriggered it.

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by j-rivero** [comment]
Seems like there are problems with nightly installation on Ubuntu, re-trigger the job to check if it is fixed or we need an intervention.

**Review by iche033 — APPROVED** [review]

**Pull request merged**
