### PR TITLE
Suggestions to model CLI (#893)

### PR DESCRIPTION
**Pull request by chapulina**
Pull request #893 is working well for me. These are some suggestions ranging from small styling nitpicks (indentation, empty spaces) to large infrastructure changes (no separate component).

Everything is a suggestion, let me know what you think, @WagnerMarcos !

Here's a summary of the changes:

* Don't create a separate `model` component, because this would make users install a new `libignition-gazebo3-model.so` library). Instead, put the new functionality into the existing `ign` component / library. I kept the yaml and ruby files separate, which I think addresses the concerns in https://github.com/ignitionrobotics/ign-gazebo/pull/893#discussion_r673146560
* (hopefully) made the new test pass on macOS by applying all the logic that's applied to `ign_TEST` (these are the changes with `CMD_TEST`, as well as `BREW*`)
* Various styling updates to the output:
    * Consistent indentation
    * Removed double spaces, or spaces at the end of a line
    * Consistent entity + name printing (added helper function `entityInfo`) - some entities missed their IDs
    * Consistent pose printing (added helper function `poseInfo`) - the inertial pose was missing RPY
* Fixed joint parent and child links, which were swapped
* Fixed running the `ign model` command without arguments (now it prints help)
* Using `ignition::gazebo` namespace to make code shorter and more readable
* Did more null pointer checking for the components
* Removed the hardcoded world entity as 1 (that assumption may change)

### CODE REVIEW

**Review by WagnerMarcos — APPROVED** [review]
Thank you for pushing this! It looks good to me.

**Comment by chapulina** [comment]
> (hopefully) made the new test pass on macOS

Argh, it's still not working on macOS:

```
/Users/jenkins/workspace/ignition_gazebo-ci-pr_any-homebrew-amd64/ign-gazebo/src/ModelCommandAPI_TEST.cc:83
Expected equality of these values:
  expectedOutput
    Which is: "\nService call to [/gazebo/worlds] timed out\nCommand failed when trying to get the world name of the running simulation.\n"
  output
    Which is: "The 'ign' command provides a command line interface to the ignition tools.\n\n  ign <command> [options]\n\nList of available commands:\n\n  help:          Print this help text.\n  gazebo:        Run and manage Gazebo.\n\nOptions:\n\n  --force-version <VERSION>  Use a specific library version.\n  --versions                 Show the available versions.\n  --commands                 Show the available commands.\nUse 'ign help <command>' to print help for a command.\n"
With diff:
@@ -1,3 +1,15 @@
+The 'ign' command provides a command line interface to the ignition tools.
+
+  ign <command> [options]
+
+List of available commands:
+
+  help:          Print this help text.
+  gazebo:        Run and manage Gazebo.
+
+Options:
 
-Service call to [/gazebo/worlds] timed out
-Command failed when trying to get the world name of the running simulation.\n
+  --force-version <VERSION>  Use a specific library version.
+  --versions                 Show the available versions.
+  --commands                 Show the available commands.
+Use 'ign help <command>' to print help for a command.\n
```

Gotta double-check that all the fixes from https://github.com/ignitionrobotics/ign-gazebo/pull/477/ are applied to the new tool

**Review by francocipollone — APPROVED** [review]
LGTM! Thanks for all the changes! 

I will take a look at CI

**Comment by chapulina** [comment]
Thanks, @francocipollone ! Let me know how I can help. I'd like to get this in today to make a Citadel release. Feel free to merge this and work on top of #893 or to work directly here

**Comment by francocipollone** [comment]
> Thanks, @francocipollone ! Let me know how I can help. I'd like to get this in today to make a Citadel release. Feel free to merge this and work on top of #893 or to work directly here

It is also failing on Ubuntu, the test file isn't finding the command. I am on it, hopefully, it will fix the problem for both platforms.

**Pull request merged**
