### PR TITLE
Resolve updated codecheck issues

### PR DESCRIPTION
**Pull request by adlarkin**
This PR is meant to resolve new codecheck issues introduced by https://github.com/ignitionrobotics/ign-cmake/pull/117.

From my understanding, the plan is to forward port the fixes here to all other ignition versions once https://github.com/ignitionrobotics/ign-cmake/pull/117 is merged.

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
This introduces lots of failures to the local `./tools/code_check.sh`:

```
  ./src/gui/PathManager.cc:23:  Found C system header after C++ system header. Should be: PathManager.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/view_angle/ViewAngle.cc:23:  Found C system header after C++ system header. Should be: ViewAngle.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/view_angle/ViewAngle.cc:24:  Found C system header after C++ system header. Should be: ViewAngle.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/transform_control/TransformControl.cc:23:  Found C system header after C++ system header. Should be: TransformControl.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/transform_control/TransformControl.cc:24:  Found C system header after C++ system header. Should be: TransformControl.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/shapes/Shapes.cc:24:  Found C system header after C++ system header. Should be: Shapes.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/shapes/Shapes.cc:25:  Found C system header after C++ system header. Should be: Shapes.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/video_recorder/VideoRecorder.cc:23:  Found C system header after C++ system header. Should be: VideoRecorder.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/video_recorder/VideoRecorder.cc:24:  Found C system header after C++ system header. Should be: VideoRecorder.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/playback_scrubber/PlaybackScrubber.cc:27:  Found C system header after C++ system header. Should be: PlaybackScrubber.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/playback_scrubber/PlaybackScrubber.cc:28:  Found C system header after C++ system header. Should be: PlaybackScrubber.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/modules/EntityContextMenu.cc:23:  Found C system header after C++ system header. Should be: EntityContextMenu.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/modules/EntityContextMenu.cc:24:  Found C system header after C++ system header. Should be: EntityContextMenu.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/modules/EntityContextMenu.cc:25:  Found C system header after C++ system header. Should be: EntityContextMenu.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/resource_spawner/ResourceSpawner.cc:26:  Found C system header after C++ system header. Should be: ResourceSpawner.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/gui/plugins/resource_spawner/ResourceSpawner.cc:27:  Found C system header after C++ system header. Should be: ResourceSpawner.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/triggered_publisher/TriggeredPublisher.cc:23:  Found C system header after C++ system header. Should be: TriggeredPublisher.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/triggered_publisher/TriggeredPublisher.cc:24:  Found C system header after C++ system header. Should be: TriggeredPublisher.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/physics/Physics.cc:27:  Found C system header after C++ system header. Should be: Physics.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/physics/Physics.cc:28:  Found C system header after C++ system header. Should be: Physics.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/physics/Physics.cc:29:  Found C system header after C++ system header. Should be: Physics.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/joint_position_controller/JointPositionController.cc:22:  Found C system header after C++ system header. Should be: JointPositionController.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/altimeter/Altimeter.cc:24:  Found C system header after C++ system header. Should be: Altimeter.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/log_video_recorder/LogVideoRecorder.cc:24:  Found C system header after C++ system header. Should be: LogVideoRecorder.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/log_video_recorder/LogVideoRecorder.cc:25:  Found C system header after C++ system header. Should be: LogVideoRecorder.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/joint_controller/JointController.cc:22:  Found C system header after C++ system header. Should be: JointController.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/battery_plugin/LinearBatteryPlugin.cc:27:  Found C system header after C++ system header. Should be: LinearBatteryPlugin.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/battery_plugin/LinearBatteryPlugin.cc:28:  Found C system header after C++ system header. Should be: LinearBatteryPlugin.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/logical_camera/LogicalCamera.cc:25:  Found C system header after C++ system header. Should be: LogicalCamera.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/user_commands/UserCommands.cc:24:  Found C system header after C++ system header. Should be: UserCommands.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/user_commands/UserCommands.cc:25:  Found C system header after C++ system header. Should be: UserCommands.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/user_commands/UserCommands.cc:26:  Found C system header after C++ system header. Should be: UserCommands.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/user_commands/UserCommands.cc:27:  Found C system header after C++ system header. Should be: UserCommands.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/wind_effects/WindEffects.cc:23:  Found C system header after C++ system header. Should be: WindEffects.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/wind_effects/WindEffects.cc:24:  Found C system header after C++ system header. Should be: WindEffects.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/wind_effects/WindEffects.cc:25:  Found C system header after C++ system header. Should be: WindEffects.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/pose_publisher/PosePublisher.cc:27:  Found C system header after C++ system header. Should be: PosePublisher.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/contact/Contact.cc:25:  Found C system header after C++ system header. Should be: Contact.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/contact/Contact.cc:26:  Found C system header after C++ system header. Should be: Contact.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/diff_drive/DiffDrive.cc:25:  Found C system header after C++ system header. Should be: DiffDrive.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/scene_broadcaster/SceneBroadcaster.cc:24:  Found C system header after C++ system header. Should be: SceneBroadcaster.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/log/LogPlayback.cc:24:  Found C system header after C++ system header. Should be: LogPlayback.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/log/LogPlayback.cc:25:  Found C system header after C++ system header. Should be: LogPlayback.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/joint_state_publisher/JointStatePublisher.cc:23:  Found C system header after C++ system header. Should be: JointStatePublisher.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/breadcrumbs/Breadcrumbs.cc:25:  Found C system header after C++ system header. Should be: Breadcrumbs.h, c system, c++ system, other.  [build/include_order] [4]
  ./src/systems/air_pressure/AirPressure.cc:24:  Found C system header after C++ system header. Should be: AirPressure.h, c system, c++ system, other.  [build/include_order] [4]
```

**Comment by adlarkin** [comment]
> This introduces lots of failures to the local `./tools/code_check.sh`

Sorry about that; I forgot that google protobuf headers are considered as standard c headers. The local check and `make codecheck` should both work now after https://github.com/ignitionrobotics/ign-gazebo/pull/443/commits/1e400bd907fbb6f8d841e668bd4f863b32c1e64d.

**Comment by adlarkin** [comment]
It looks like ubuntu ci failed. When I took a look at jenkins, it says the following:

```
apt-get was unable to locate some packages needed for the build. It might be a problem with setup the repositories or for exotic arches the packages might now exists at all.
```

I'm also seeing [test failures](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-homebrew-amd64/4075/testReport/) on homebrew ci. It looks like one of the tests might be an issue that already exists (`PeerTracker` has failed for the past 3 builds), but another one of the tests might be new (`INTEGRATION_level_manager`).

Could it be possible that fixing the headers broke the tests somehow, or are these false negatives? `INTEGRATION_level_manager` passes all tests when I run it locally.

**Comment by chapulina** [comment]
> ubuntu ci failed

I think this is unrelated to this PR and should be fixed by https://github.com/ignition-tooling/release-tools/pull/339. Note how it's trying to install dependencies that aren't needed by `ign-gazebo2` and are only available from nightlies, like `libignition-rendering5-dev`.

**Comment by adlarkin** [comment]
I see - can this be merged then?

**Review by mjcarroll — APPROVED** [review]

**Comment by adlarkin** [comment]
@chapulina it looks like merging is blocked until your request for changes is lifted, so I re-requested a review from you.

**Comment by chapulina** [comment]
@osrf-jenkins run tests one more time please

**Review by chapulina — APPROVED** [review]

**Pull request merged**
