### PR TITLE
4 to 5

### PR DESCRIPTION
**Pull request by ahcorde**
# ➡️ Forward port

Port 4 to 5

Branch comparison: https://github.com/ignitionrobotics/ign-gazebo/compare/ign-gazebo5...ign-gazebo4

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

Require https://github.com/osrf/sdformat/pull/598

### CODE REVIEW

**Comment by chapulina** [comment]
There are multiple new test failures that seem to be related to slip (ackermann, diff drive, wheel slip...). Do you know if we need a new `ign-physics` release to fix those, @scpeters ?

**Comment by scpeters** [comment]
> There are multiple new test failures that seem to be related to slip (ackermann, diff drive, wheel slip...). Do you know if we need a new `ign-physics` release to fix those, @scpeters ?

it could be related to the `SpeedLimiter` changes in #833 and #837 (cc @LolaSegura @francocipollone). I'll take a look this afternoon

**Comment by chapulina** [comment]
I'm not being able to reproduce this locally, I've tried a few different combinations of branches and dependencies.

I re-ran CI for the `ign-gazebo5` branch, and it looks like the tests started failing there:

https://github.com/ignitionrobotics/ign-gazebo/runs/2916861022?check_suite_focus=true

```
  The following tests FAILED:
  	 51 - INTEGRATION_ackermann_steering_system (Failed)
  	 61 - INTEGRATION_breadcrumbs (Failed)
  	 73 - INTEGRATION_diff_drive_system (Failed)
  	107 - INTEGRATION_logical_camera_system (Failed)
  	129 - INTEGRATION_performer_detector (Failed)
  	131 - INTEGRATION_physics_system (Failed)
  	155 - INTEGRATION_wheel_slip (Failed)
```

The good news is that the failures are not introduced by this PR. The bad news is that we have all these new test failures to deal with.

I suggest we ignore these failures for this PR, and look into them on top of the release branches.

For completeness, I've triggered Jenkins CI for all stable branches:

* `ign-gazebo5`: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo5-bionic-amd64/17/)
* `ign-gazebo4`: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo4-bionic-amd64/82/)
* `ign-gazebo3`: [Build Status](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-bionic-amd64/135/)

**Comment by chapulina** [comment]
> I've triggered Jenkins CI for all stable branches:

Well, at least the failures are happening only on Edifice.

**Review by chapulina — APPROVED** [review]
LGTM, I didn't notice any new test failures and the changes look ok.

**Pull request merged**
