### PR TITLE
👩‍🌾 Enable Focal CI

### PR DESCRIPTION
**Pull request by chapulina**
# 🎉 New feature

## Summary

Enable Focal GitHub actions CI (about time!).

When merging forward to Dome, the approach on #503 will be taken.

## Test it

Make a commit and wait for CI results :wink: 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

---

https://github.com/osrf/buildfarmer/issues/161

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
These tests are failing

```bash
  	 27 - UNIT_SimulationRunner_TEST (SEGFAULT)
  	 61 - INTEGRATION_contact_system (SEGFAULT)
  	 65 - INTEGRATION_diff_drive_system (Failed)
  	131 - INTEGRATION_wheel_slip (Failed)
```

**Comment by chapulina** [comment]
As discussed with the team, we're disabling the tests that rely on slip for now, see https://github.com/ignitionrobotics/ign-physics/issues/49.

I couldn't figure our a way of disabling according to Ubuntu version, so I'm disabling it for all Linux. (`uname` may give the wrong answer when running in a Docker container).

**Review by ahcorde — CHANGES_REQUESTED** [review]
```
unused variable ‘wheelNormalForce’ [-Wunused-variable] const double wheelNormalForce = 32; ^~~~~~~~~~~~~~~~
```

and 

```
unused variable ‘mass’ [-Wunused-variable] const double mass = 14.5; ^--
```

**Comment by chapulina** [comment]
All :green_circle: now! :tada:

**Review by jennuine — APPROVED** [review]

**Pull request merged**
