### PR TITLE
Fixed <uri>s in sdf files

### PR DESCRIPTION
**Pull request by ahcorde**
I'm getting some errors because of theses spaces

Signed-off-by: Alejandro Hernández <ahcorde@gmail.com>

### CODE REVIEW

**Comment by chapulina** [comment]
@ahcorde , how did you install SDFormat? This PR should have fixed this: https://github.com/osrf/sdformat/pull/359

**Comment by ahcorde** [comment]
yes, I have this PR in. I will check it again.

**Comment by chapulina** [comment]
@ahcorde , I don't have problems with these URIs using pre-release debs on Bionic or Focal.

**Comment by scpeters** [comment]
try `brew outdated` to see if you have the latest prerelease of `sdformat10`

**Comment by scpeters** [comment]
yeah, I believe this PR shouldn't be necessary due to https://github.com/osrf/sdformat/pull/359

**Comment by chapulina** [comment]
@ahcorde , I'll close this for now, but let us know if the problem reappears for you.

**Pull request closed without merging**
