### PR TITLE
Remove static for maps from Factory.hh

### PR DESCRIPTION
**Pull request by shameekganguly**
# 🦟 Bug fix

Fixes an issue where dlopen can fail with segfault due to static map variables in Factory.hh.
Fix is to simply remove the static qualifiers. This does not have any significant usage impact and a minor perf impact as the Factory class is already a singleton.

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
Thank you for the pull request. This is causing CI to fail, does it work locally for you?

```
/var/lib/jenkins/workspace/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/ign-gazebo/include/ignition/gazebo/components/Factory.hh:313:59: error: ‘namesById’ declared as an ‘inline’ field
     public: inline std::map<ComponentTypeId, std::string> namesById;
                                                           ^~~~~~~~~
/var/lib/jenkins/workspace/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/ign-gazebo/include/ignition/gazebo/components/Factory.hh:318:9: error: ‘runtimeNamesById’ declared as an ‘inline’ field
         runtimeNamesById;
         ^~~~~~~~~~~~~~~~
```

**Comment by mjcarroll** [comment]
Ping @shameekganguly , I think you also meant to remove `inline` here?

**Comment by shameekganguly** [comment]
Yep, sorry about that! I will create a new PR with the fix.

**Comment by shameekganguly** [comment]
Should be able to pass all tests with the new fix.

**Review by chapulina — CHANGES_REQUESTED** [review]
This breaks ABI and can't be merged into a stable release. Can it be retargeted to `main` (Edifice)?

See the ABI test results: https://build.osrfoundation.org/job/ignition_gazebo-abichecker-any_to_any-ubuntu_auto-amd64/3271/API_5fABI_20report/

**Comment by mjcarroll** [comment]
> This breaks ABI and can't be merged into a stable release. Can it be retargeted to main (Edifice)?

Discussed offline, `main` is fine, retargeted.

**Comment by chapulina** [comment]
@osrf-jenkins run tests again

**Review by chapulina — APPROVED** [review]
Better late than never, thanks for the PR!

**Pull request merged**
