### PR TITLE
Combined server gui

### PR DESCRIPTION
**Pull request by nkoenig**
This change `ign gazebo` to run the server and GUI in the same process. The goal is to improve performance (less protobuf serialization), and help with video recording.

### CODE REVIEW

**Review by jennuine — COMMENTED** [review]
Unfortunately, I still see the same pause/jump
after_natefix

**Review by chapulina — CHANGES_REQUESTED** [review]
I don't think we should change the default behavior on Citadel. This is a behavior change that could affect logic that's counting on having separate processes.

How about making it an option?

**Comment by nkoenig** [comment]
> I don't think we should change the default behavior on Citadel. This is a behavior change that could affect logic that's counting on having separate processes.
> 
> How about making it an option?

Do you know what things are dependent on separate processes? I would like to know what all would break.

**Comment by chapulina** [comment]
> Do you know what things are dependent on separate processes?

The main thing that comes to mind is the rendering singleton. The current implementation relies on having 2 separate scenes that are synced through the state topic, and they have separate rendering threads. If the render engine treats these 2 scenes as the same one, it could crash if 2 threads are writing to the scene at the same time.

Using different scenes for GUI and server means that they can be slightly different. For example, right now they can have different background colors. I don't think this is very important though. On the flip side, if we can remove the reliance on the `SceneBroadcaster` for the GUI 3D scene, that system can be significantly throttled, because widgets like the entity tree and component inspector don't need 60Hz.

I can't think of anything else right now. In any case, we never know what users may be doing in their plugins.

**Comment by nkoenig** [comment]
Mentioning rendering brings to mind that this probably also breaks sensor generation.

**Comment by nkoenig** [comment]
Doesn't solve the intended purpose.

**Pull request closed without merging**
