### PR TITLE
Choose Render Engine from Cmd Line

### PR DESCRIPTION
**Pull request by JShep1**
This currently supports only rendering engines native to ignition-rendering (Ogre, Ogre2).  Still need to add `--rendering-engine-client` and `--rendering-engine-server`

### CODE REVIEW

**Comment by chapulina** [comment]
I see this is targeting master. Do you think it would be possible to target Citadel?

**Comment by JShep1** [comment]
> I see this is targeting master. Do you think it would be possible to target Citadel?

It will require an update to the `runServer` function signature (https://github.com/ignitionrobotics/ign-gazebo/pull/330/files#diff-c1dfe0042975f8dbb40b802e04cc4bd1R54-R59), I initially was going to set the old `runServer` to be deprecated and overload the function, but since `ign.cc` is technically C, function overloading is not allowed.  Can we simply update the function signature in Citadel?  I wasn't quite sure so I initially targeted at Dome

**Comment by chapulina** [comment]
> It will require an update to the runServer function signature

Oh, `ign.hh` is not installed, so feel free to change it as you need on any version :wink:

**Comment by JShep1** [comment]
> Oh, `ign.hh` is not installed, so feel free to change it as you need on any version

Sounds good, I'll retarget to Citadel

**Comment by JShep1** [comment]
Closing to retarget at Citadel [here](https://github.com/ignitionrobotics/ign-gazebo/pull/331)

**Pull request closed without merging**
