### PR TITLE
Generate valid topics everywhere (support names with spaces)

### PR DESCRIPTION
**Pull request by chapulina**
This wraps up #239.

I went through the codebase and updated any topics and services I found to convert topics to valid ones if possible.

The `spaces.sdf` world has some entities with empty spaces, and wouldn't work correctly without this PR, mainly because of the spaces in the world name.

I also added the `validTopic` helper function which is handy to use when we have fallbacks for the topic. For example, when we accept a `<topic>` option from SDF, and fallback to a name-generated topic in case none is provided on SDF. Both these topics need to be validated, so the function helps with that.

We need to be mindful of this when adding new topics and plugins!

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]
LGTM

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Review by JShep1 — APPROVED** [review]
Looks good with tests passing locally.  There's a failure in CI, it may be a flaky test.

**Comment by chapulina** [comment]
I'll wait for the `ign-gui 4.1.1` release before merging this, otherwise `spaces.sdf` won't work well.

**Pull request merged**
