### PR TITLE
3 ➡️ 4

### PR DESCRIPTION
**Pull request by chapulina**
Forward-port `ign-gazebo3` to `ign-gazebo4`. See comparison:

https://github.com/ignitionrobotics/ign-gazebo/compare/ign-gazebo4...ign-gazebo3

Needs this PR to be merged and released first: https://github.com/ignitionrobotics/ign-physics/pull/129

### CODE REVIEW

**Comment by chapulina** [comment]
`ign-physics 3.1.0` is out, this should be unblocked.

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Review by azeey — COMMENTED** [review]
Looks like the changes in #314 to fix the diff drive tests are not compatible with the changes in #357. Reverting the changes in `test/integration/diff_drive_system.cc` from #314 fixes the test for me locally.

**Comment by chapulina** [comment]
> Reverting the changes in test/integration/diff_drive_system.cc from #314 fixes the test for me locally.

Thanks for figuring this out, @azeey. The test was failing locally for me and I was thinking I had the wrong DART version.

Reverted in 0ab6d35 and confirmed that the test is fixed for me locally :+1:

**Review by azeey — APPROVED** [review]

**Pull request merged**
